### ISSUE TITLE
Language preference modification

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1381] opened 2017-01-18 10:11 UTC
It is not possible to modify the default language in an user's profile.

**Comment by asaunier** [comment] 2017-01-18 10:24
It's not a language preference. It's the language of the current document (as for waypoints, routes, etc.) => it is not possible to change the language of an existing document.

As for other document types, you may create a version of the profile in another language by clicking on the "plus" button > "Translate into another language".

At the moment there is no language preference. Anyway, preferences are not set in the user's profile but in the preferences page: https://www.camptocamp.org/preferences

Not a bug then => please close the issue, thanks.

**Closed** 2017-01-18 10:28 UTC
Labels: bug
