### ISSUE TITLE
Message on sign up

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#592] opened 2016-09-05 13:14 UTC
When you register a new account, you see a message "Success" but you don't know that you are getting an email with a confirmation link to activate the account.

**Comment by asaunier** [comment] 2016-09-05 13:18
There must have been a regression because on the demo you actually get a message saying you will receive a validation email:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/18249009/fbbb9572-737b-11e6-8499-7b24007ef657.png)

Or maybe it's a translation problem?

**Comment by tsauerwein** [comment] 2016-09-05 13:20
Yes, in the English translation it is simply "Register success":
https://github.com/c2corg/v6_ui/blob/d5d548c7db5163e9aaf6389b76b2e70b83bf28ba/c2corg_ui/static/js/auth/auth.js#L229

**Comment by asaunier** [comment] 2016-09-05 13:31
So it's simply a translation problem. Can we close the issue then? Or maybe we should update the string in the code?

**Comment by tsauerwein** [comment] 2016-09-05 13:34
> Or maybe we should update the string in the code?

It should be updated in the code.

**Comment by asaunier** [comment] 2016-09-05 13:38
Really?
I think all strings should be translated using Transifex, including in English (else one would have to edit the source code to update the english strings).

**Comment by tsauerwein** [comment] 2016-09-05 13:42
Isn't it done like this for this project? You provide the default English translation in the code/template and do the translations on Transifex.

**Comment by asaunier** [comment] 2016-09-05 13:45
Nope, in Transifex the source strings are provided as "en_US" and then we have 7 target languages including "en". This way the EN translations are not necessarly the same than in the source code.

**Comment by tsauerwein** [comment] 2016-09-05 13:48
And do you think it is a good idea to repeat the English translation?

**Comment by asaunier** [comment] 2016-09-05 13:52
If the translation string is exactly the same than the source string, it is not needed to duplicate it.
But at least the translation team may change the EN translations if they want to without changing the source code.

**Comment by tsauerwein** [comment] 2016-09-05 13:54
> If the translation string is exactly the same than the source string, it is not needed to duplicate it.

Exactly. So we should try as far as possible to have the good translation in the code/template.

**Comment by asaunier** [comment] 2016-09-05 13:56
Please change the source string if you want.

**Comment by shortoland** [comment] 2016-09-06 07:49
Please tell me if I have to update the translation in Transifex (which is very easy to do).
Anyway, all translations will have to be checked in the website, as translators don't always know the exact context of usage of the strings to be translated.

**Comment by asaunier** [comment] 2016-09-06 07:58
> Please tell me if I have to update the translation in Transifex (which is very easy to do).

I don't think you have anything to do. Perhaps check that the string id has correctly been updated in Transifex (I think you have to wait that the PR is merged).

**Comment by shortoland** [comment] 2016-09-06 08:12
@asaunier OK !

**Closed** 2016-09-07 14:53 UTC

**Comment by asaunier** [comment] 2016-09-07 15:46
It seems it's a problem to change interface strings that were already translated in Transifex. When changing the string in the source code, the extraction tool does not recognize it's the same string in the translation dictionary and push it as a new one to Transifex, the old one being lost (even though a translation was available in Transifex).

So it's better not to update translation strings in the source code if there's a chance they have been translated in Transifex.
