### ISSUE TITLE
"Add an outing" button in route detail view

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#269] opened 2016-04-05 11:47 UTC
When clicking on "Add an outing" in route detail view, the opened URL should contain a parameter giving the document_id of the route.
This route should then be directly listed in the associated routes of the outing.

Related to https://github.com/c2corg/v6_ui/issues/227

**Comment by asaunier** [comment] 2016-04-08 12:34
Related to https://github.com/c2corg/v6_ui/issues/256 as well

**Comment by fjacon** [comment] 2016-04-28 10:41
Duplicate of https://github.com/c2corg/v6_ui/issues/198

**Closed** 2016-04-28 10:41 UTC
Labels: Guidebook, high prio
