### ISSUE TITLE
'Ajouter à mes favoris' does not work

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#647] opened 2016-09-22 06:09 UTC
When i click on 'Ajouter à mes favoris' on a route document, nothing happens. The picto is not modified. I did not find any information about my 'favoris' in my profile.

**Comment by asaunier** [comment] 2016-09-23 07:48
Duplicate of https://github.com/c2corg/v6_ui/issues/645
Closing for the same reason

**Closed by asaunier** 2016-09-23 07:48 UTC
