### ISSUE TITLE
Problems with versions of a document

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#408] opened 2016-06-11 14:35 UTC
- [x] Date/time is wrong:
  I modify an outing (see outings/history/736972/fr). The modification time is wrong: 06:mm instead of 16:mm
- [x] Pb to display outing
  In "Comparaison des documents" page (see outings/diff/736972/fr/1164793/1164795)
  When I click on "Version du....", I get an "Internal Server Error".
- [x] It should be possible to display the current version of the outing from this page.

**Comment by asaunier** [comment] 2016-06-12 20:11
> It should be possible to display the current version of the outing from this page.

Yep, I have also noticed that it's not easy to go back to the history page of a document when viewing diffs.

**Comment by fjacon** [comment] 2016-06-29 07:10
Display current version is a nice to have (extra)

**Comment by tsauerwein** [comment] 2016-06-29 07:16
> Display current version is a nice to have (extra)

If I understand correctly this is simply about adding a link to go back?

**Comment by asaunier** [comment] 2016-06-29 08:28
* [ ] When showing on old version of a document, the message warning that the current page is an old one is not displayed correctly (probably a CSS default introduced in the meantime). This the screeshot below:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/16445697/2f443d54-3de4-11e6-8898-ed2c57466cfa.png)

**Comment by asaunier** [comment] 2016-06-29 08:35
> If I understand correctly this is simply about adding a link to go back?

When you see a diff page, for instance http://c2corgv6.demo-camptocamp.com/routes/diff/51225/fr/51910/335059 you have no direct way to see the document itself.
Well you could click on the link toward one of the diffed version and then you have links towards the last version of the document. I agree this is not critical.

**Comment by asaunier** [comment] 2016-06-29 08:41
* [ ] The "title_prefix" (main waypoint name) is missing for routes in the history pages and diff pages.

Concerning the versions/history page, see also the radio button issue at https://github.com/c2corg/v6_ui/issues/344

**Comment by ginold** [comment] 2016-07-04 13:55
@loicperrin are you still getting an internal server error when comparing 2 outings? I cannot access the two you posted and can't find any other two that give such an error.
I will mark this as resolved for now.

**Comment by loicperrin** [comment] 2016-07-04 20:20
I still have this pb: In "Comparaison des documents" page (see outings/diff/736972/fr/1164793/1164795)
When I click on "Version du....", I get an "Internal Server Error".
See http://c2corgv6.demo-camptocamp.com/outings/diff/736956/fr/1164743/1164744

And the Date/time is still wrong too.

**Comment by asaunier** [comment] 2016-07-22 12:14
What about the "main waypoint name" missing for routes in the history and diff pages?
https://github.com/c2corg/v6_ui/issues/408#issuecomment-229293732

**Comment by shortoland** [comment] 2016-07-22 12:31
According to me it's OK, but I am not 100% sure of my understanding.

![image2](https://cloud.githubusercontent.com/assets/20488365/17057201/d3980e8a-5018-11e6-9d33-7c756e2baa32.png)

Am I supposed to click the checkbox " The "title_prefix" (main waypoint name) is missing for routes in the history pages and diff pages." to confirm bug fixing ?

**Comment by asaunier** [comment] 2016-07-22 12:38
Your example is an outing (which has a standard title). The problem is for routes => routes have a base name (for instance "Face N" or "Couloir Whymper") to which the main waypoint name ("Aiguille Verte") is appended.
See http://c2corgv6.demo-camptocamp.com/routes/54309/fr
http://c2corgv6.demo-camptocamp.com/routes/history/54309/fr

**Comment by shortoland** [comment] 2016-07-22 12:47
OK, as this ticket was first concerning outings, I just checked those (but you changed the title then ;-)
Issue is still there for routes.

**Comment by loicperrin** [comment] 2016-07-22 20:33
* [ ] Another very minor pb: in comparison page, when we click on the last version, the message "Vous consultez une ancienne version de ce document." is displayed.

**Comment by asaunier** [comment] 2016-07-25 06:06
> Another very minor pb: in comparison page, when we click on the last version, the message "Vous consultez une ancienne version de ce document." is displayed.

Could you give an example URL? I cannot reproduce this behaviour.

**Comment by loicperrin** [comment] 2016-07-25 11:50
outings/736952/fr/1164735: the message is displayed, whereas it is the last version of outings/736952

**Comment by asaunier** [comment] 2016-07-25 11:58
OK thanks.

"outings/736952/fr/1164735" contains the version number, if the version number is provided, the message is displayed (don't know if there are other ways to figure out if a version is an archived one or the most recent one).

Please note that in the history page the link towards the most recent version contains no version number and thus no message.

But that's true that in a diff page such as http://c2corgv6.demo-camptocamp.com/routes/diff/54309/fr/878921/1163812 if the right version is the most recent version of a document, the link towards this version contains the version number (as you did report it - sorry for misreading).

**Comment by stef74** [comment] 2016-07-27 07:41
It's ready for test or not ?

**Comment by stef74** [comment] 2016-07-29 09:07
@fjacon @asaunier @ginold what is the status ?

**Comment by stef74** [comment] 2016-08-22 12:20
@fjacon what is the status of this issue ?

**Comment by fjacon** [comment] 2016-08-22 12:44
I think it can be tested.

**Comment by stef74** [comment] 2016-08-22 13:03
@loicperrin please test

**Comment by shortoland** [comment] 2016-08-24 15:49
@stef74 The 2 issues (WP name not displayed when comparing routes & unwanted old version warning message) are not solved.

**Comment by loicperrin** [comment] 2016-08-24 21:19
Not solved indeed.

**Comment by asaunier** [comment] 2016-09-28 17:53
> @stef74 The 2 issues (WP name not displayed when comparing routes & unwanted old version warning message) are not solved.

* "unwanted old version warning message" (actually it's because of an unwanted URL parameter) should be fixed by https://github.com/c2corg/v6_ui/pull/665
* "WP name not displayed when comparing routes" => this is a complicated problem because the API does not provide this information, because the main waypoint info is not available in archived versions (I think). Perhaps the API should make an additional query to the database to get the current route (resp. document) name and add it to its response. But that adds quite a lot of complexity. Honestly I think this is not a critical issue, we should skip it. Or at least set it to low priority (not for 6.0).

**Comment by stef74** [comment] 2016-11-02 09:02
@loicperrin @shortoland please test and close

**Comment by shortoland** [comment] 2016-11-03 17:44
@stef74:

"unwanted old version warning message" is solved.

"WP name not displayed when comparing routes": following @asaunier comments, I think we can skip this minor issue.

So I close the ticket. @loicperrin, feel free to reopen if you disagree.

**Closed by shortoland** 2016-11-03 17:44 UTC
Labels: fixed and ready for testing, Guidebook, low prio
