### ISSUE TITLE
Problem on Hover on icon with Chrome

### ISSUE THREAD

**Issue by dribagnac** [c2corg/v6_ui#970] opened 2016-11-23 10:44 UTC
Take this page (for example)
http://www.demov6.camptocamp.org/articles/121965/fr/credits

   When I hover on the icons of activity (see screenshot), they move inside the block when I hover with the mouse.

   Bug detected only with Chrome 54 (tested on Win 10)
   Works fine with Firefox (ie icons do not move).

![screenshot-www demov6 camptocamp org 2016-11-23 11-41-49](https://cloud.githubusercontent.com/assets/995825/20558809/2f79ad20-b172-11e6-84b9-d3c42abe2280.png)

**Comment by besson-genostar** [comment] 2016-11-25 14:34
Tested this on FF 49.0.2, Chrome 50.0.2661.94, cannot reproduce. Maybe this is specific to a recent chrome version?
In the meantime, I can reproduce such strange behaviour on FF on desktop (but resized to a small screen) for the floating icons. I think it is related to the tooltips (maybe it should be created in another part of the body - can we specify that with angular?).

**Comment by brunobesson** [comment] 2016-11-25 14:35
Tested this on FF 49.0.2, Chrome 50.0.2661.94, cannot reproduce. Maybe this is specific to a recent chrome version?
In the meantime, I can reproduce such strange behaviour on FF on desktop (but resized to a small screen) for the floating icons. I think it is related to the tooltips (maybe it should be created in another part of the body - can we specify that with angular?).

**Comment by dribagnac** [comment] 2016-11-25 14:51
This problem is only visible on Chrome 54 (not tested with older version).
With FF 50, Edger it is working fine

**Comment by asaunier** [comment] 2016-12-04 09:38
Tested with Chrome 54 and 55.
Actually no problem if the icons are on the same line.
If the line is too long and had to be split into 2 lines, hovering the last icon of the first line actually makes it jump to the next line. But that's it.

**Comment by stef74** [comment] 2016-12-04 17:12
Honestly we need to do something ?

**Comment by brunobesson** [comment] 2016-12-05 08:32
I'll have a look sometimes at how to handle tooltips on phone screens. They are e.g. activated in the sidemenu only for tablets, maybe we could do something similar for button tooltips?

**Comment by ginold** [comment] 2016-12-22 15:15
the issue has been fixed thanks to a recent update

**Comment by stef74** [comment] 2016-12-22 16:35
@brunobesson coule you confirm'and close ?

**Comment by brunobesson** [comment] 2016-12-22 19:50
I confirm the issue is fixed as a side effect of the work on cards. Closing.

**Closed by brunobesson** 2016-12-22 19:50 UTC
Labels: fixed and ready for testing
