### ISSUE TITLE
Problem with advance search layout in mobile

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#785] opened 2016-10-24 08:58 UTC
![img_0761](https://cloud.githubusercontent.com/assets/3962997/19639354/74cb0ad8-99d8-11e6-9d0a-db840f493666.PNG)

For me the problem is that you show the map AND the advance filter ... the simple way is not show the map when you show filter ?

**Comment by asaunier** [comment] 2016-10-24 09:04
Duplicate of https://github.com/c2corg/v6_ui/issues/657
Please move your comment to the latter issue.
Closing.

**Closed by asaunier** 2016-10-24 09:04 UTC
