### ISSUE TITLE
Problems with advanced search

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#762] opened 2016-10-20 22:27 UTC
- [ ] Sometimes (not always, but at least 50% of my trials) I cannot check or uncheck an activity in Advanced search filter.
- [ ] I have also seen problems with vertical scrollbar on the right of criteria: sometimes, I cannot scroll to the bottom of the list

**Comment by tsauerwein** [comment] 2016-10-21 08:39
> Sometimes (not always, but at least 50% of my trials) I cannot check or uncheck an activity in Advanced search filter.

Same issue as the 2nd point in https://github.com/c2corg/v6_ui/issues/655?

> I have also seen problems with vertical scrollbar on the right of criteria: sometimes, I cannot scroll to the bottom of the list

Same as https://github.com/c2corg/v6_ui/issues/692?

**Comment by asaunier** [comment] 2016-10-21 08:53
It seems this issue is a duplicate of the issues @tsauerwein mentioned.
If not exactly, it would make sense to move those 2 points in those issues and to close the current one (always make sure problems are not already reported before creating an issue :P ). Thanks!

**Comment by loicperrin** [comment] 2016-10-21 21:07
>Same as #692?

Yes !

> Same issue as the 2nd point in #655?

Not exactly: I have seen this problem in a simpler use case. But probably it is the same cause.

=> I close this ticket

**Closed** 2016-10-23 16:03 UTC
Labels: advanced Search, bug
