### ISSUE TITLE
Pictures are not displayed in the feed for new outings

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#947] opened 2016-11-20 07:31 UTC
Example : https://www.demov6.camptocamp.org/outings/822355/fr/col-de-fenestral-combe-s#/&gid=1&pid=3
Christian created an outings with pictures, the outing is then in the feed but the pictures are not displayed.
If additional pictures are added (I added one) then one more event in the feed with the picture.

Expectation : pictures should be displayed in the feed with the event "creation of an outing"

**Comment by tsauerwein** [comment] 2016-11-20 15:21
Closing as a duplicate of https://github.com/c2corg/v6_ui/issues/816

**Closed by tsauerwein** 2016-11-20 15:21 UTC
