### ISSUE TITLE
Cannot reupload a GPS track

### ISSUE THREAD

**Issue by LaurentBonnaud** [c2corg/v6_ui#1320] opened 2017-01-06 20:24 UTC
Hi,

the following sequence of actions lead to a bug that prevented me from uploading a GPS track:

1. create a new outing
1. upload a GPS track
1. move a GPS point by mistake (very easy to do while trying to drag the map)
1. click on "Reset Feature" (hoping to undo the mistake)
1. try to reupload the track

Fortunately I could upload the GPS track after saving and reediting the outing, but it is needlessly complicated.

**Comment by brunobesson** [comment] 2017-01-06 20:27
Thx Laurent, but this issue is also already known and an issue has been assigned (no will to look for it and reference it though...).
Your feedback is welcome, but please check first of there isn't already an issue :wink:

**Comment by LaurentBonnaud** [comment] 2017-01-06 20:35
I did check (only open issues) but did not find it.
Can you please point me to the already reported issue ?
Is it possible to merge issues in the github bug tracker ?

**Comment by brunobesson** [comment] 2017-01-06 20:39
#1119
But after reading it again, I confess it isn't exactly the same, my apologies.
Maybe we should investigate the problem a little more and create an issue (out update the existing one) compiling both issues, mine and yours.

**Comment by LaurentBonnaud** [comment] 2017-01-06 20:54
No problem, both issues look extremely similar (if not identical).
I only looked for the "GPS" keyword, not "GPX".

**Comment by asaunier** [comment] 2017-01-10 09:37
> No problem, both issues look extremely similar (if not identical).

@LaurentBonnaud @brunobesson I don't really see the difference between this issue and https://github.com/c2corg/v6_ui/issues/1119

The only "difference" is that in #1119 another GPX track is used in the last steps but that looks exactly the same problem.

Actually I cannot reproduce the problem with the last version of the master branch in Chromium 55 and Firefox 50: after resetting the initial track, I have uploaded the same file again and it worked. I have also tested on the demo: http://www.demov6.camptocamp.org/outings/828340/fr/wetterhorn-par-le-rosenlauigletscher

What browsers do you use?

> the following sequence of actions lead to a bug that prevented me from uploading a GPS track

Could you precise the problem? What happens when you upload the second GPS track? Error? The new track is not displayed?

**Comment by brunobesson** [comment] 2017-01-12 10:53
Using chrome 55 (or FF 50.1):

* create a new route
* upload GPX file > it is added on the map
* click reset > geometry is reset
* upload GPX > nothing happens, the new track is not displayed

Nothing happens in the console.

**Comment by asaunier** [comment] 2017-01-12 11:06
I generally don't observe this problem in my Chromium 55 nor FF 50.1 but I admit I have experienced it in my FF once (but I cannot reproduce it ever since).

Do you think we can close https://github.com/c2corg/v6_ui/issues/1119 as duplicate?

**Comment by brunobesson** [comment] 2017-01-12 11:08
Closing, and reporting 6.2 milesone.

**Comment by fjacon** [comment] 2017-02-24 11:19
can anybody still reproduce this ?

**Comment by brunobesson** [comment] 2017-02-24 11:24
@fjacon yes, with the exact same protocol described.

**Comment by asaunier** [comment] 2017-05-18 15:09
> Using chrome 55 (or FF 50.1):
create a new route
upload GPX file > it is added on the map
click reset > geometry is reset
upload GPX > nothing happens, the new track is not displayed

Is this problem still valid? I can no longer reproduce it following the steps above with recent Chrome or FF, both when creating a route or editing an existing one with a gps track.
I think changes have occured in the map tool in the mean time, for instance there is now a "Clear" button in addition to the "Reset" button, appearing when editing a route with a gps track.

**Comment by fjacon** [comment] 2017-05-31 11:39
Not reproductible

**Closed** 2017-05-31 11:39 UTC
Labels: bug, bug_SA, Map
