### ISSUE TITLE
Feed improvements

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#754] opened 2016-10-19 12:32 UTC
as from #731 

- [ ] what happens if users scroll the feed, clicks on a card (open a new page) and then want to go back to the feed by pressing the "back" button: will the feed be reset or will it be restored at the same place?
Perhaps we will have to pass some kind of permalink to the address bar?

- [x] show a message when no more feed (error while fetching, loading feed, no more feed)

**When viewing the homepage feed, it would be useful for authenticated users:**

- [x] to be reminded that they have filters and "followship" enabled
- [x] to provide them a shortcut (button?) towards their preferences interface
- [x] to provide them a button (or checkbox?) to temporarly disable the filters (in order to see the standard feed without having to make changes in their preferences)

Perhaps it could be done later (in a next PR) but at least it's worth taking this future evolutions into account for writing the current code. Especially the apiservice related part.
For instance temporarly disabling the filters could be done by:

- [x]  switching to /feed until the "disable filters" tool is turned of. When switching on/off the "disable filters" tool, it's probably more relevant to reset the feed (not only to apply the change to the subsequent infinite scrolling calls).

- [x] create a partial template with the feed
- [x] remove app-loading directive

**Comment by asaunier** [comment] 2016-10-19 19:09
* [ ] it seems that the user name used in the action descriptions is the username (or login?). It would be more relevant to use the ``name`` attribute ("guidebook name") as in the outing cards:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/19533514/606ff256-9640-11e6-9ff4-daf2ef88d737.png)

**Comment by ginold** [comment] 2016-10-20 07:34
> ... as in the outing cards

the ones in the feed ARE cards, so they are no different and they use `doc['author']['name']`, not 'username'

**Comment by asaunier** [comment] 2016-10-20 07:45
The problem is not in the card but in the comment above: "foobar has created a new outing" => the latter should use ``name`` as well.

Actually I think that the login should never be passed to (and used by) the UI, see https://github.com/c2corg/v6_api/issues/436
Only ``name`` and ``forum_username`` are relevant in the UI.

**Comment by asaunier** [comment] 2016-10-20 07:48
* [ ] Another point with feed improvement: are images (with filenames) supported? Please note that the images feed cards are a bit different then in the advanced search since they may contain several image filenames.

**Comment by ginold** [comment] 2016-10-20 10:24
if a user changes the feed type, disables the filters and so on - should the complete feed be reloaded ? or just add the other, new documents at the end of the feed?

**Comment by asaunier** [comment] 2016-10-20 10:27
> should the complete feed be reloaded ?

Yes

**Comment by asaunier** [comment] 2016-10-25 09:49
* [ ] It seems the "add an outing" button at the beginning of the homepage feed is not translated.

**Comment by stef74** [comment] 2016-10-25 10:00
@shortoland could you translate ?

**Comment by stef74** [comment] 2016-10-25 10:01
@ginold what is the ramaining job on this issue ?

**Comment by asaunier** [comment] 2016-10-25 10:04
> what is the ramaining job on this issue ?

All points above that are not checked.

**Comment by asaunier** [comment] 2016-10-25 10:07
> @shortoland could you translate ?

It's not a translation issue (the string is alread available in the page header). Most likely the string is not marked as to be translated in the source code. See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/feed.html#L19 (missing "translate" directive).

**Comment by asaunier** [comment] 2016-10-25 21:42
* [ ] weird action description:
<img width="555" alt="capture d ecran 2016-10-25 a 23 41 22" src="https://cloud.githubusercontent.com/assets/1192331/19705411/af2c4996-9b0c-11e6-8a5b-3744f55296e1.png">

**Comment by ginold** [comment] 2016-10-26 09:01
^ maybe look at #786

**Comment by asaunier** [comment] 2016-10-27 12:54
It seems that all points of this issue has been addressed, except

> what happens if users scroll the feed, clicks on a card (open a new page) and then want to go back to the feed by pressing the "back" button: will the feed be reset or will it be restored at the same place?
Perhaps we will have to pass some kind of permalink to the address bar?

I suggest to wait for the user feedbacks before doing anything.

Closing the issue, please reopen if something is still missing.

**Closed by asaunier** 2016-10-27 12:54 UTC
