### ISSUE TITLE
A route without main WP neither GPX track, has no georef neither associated area

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1026] opened 2016-11-27 10:19 UTC
When we create a route, if we associate some WP but we don't define any main WP, and we don't add a GPX track, the route has no georef and no associated area.
Then, the route can't be found by the search tool when we filter on the map extend (= default map config).

Moreover, on the page of a route without main WP neither GPX track, no WP picto appear on the embedded map. See https://github.com/c2corg/v6_ui/issues/896
But if we add a GPX track, the WP and the track are shown on the map (the route has a georef in this case).

**Comment by asaunier** [comment] 2016-11-28 10:00
> When we create a route, if we associate some WP but we don't define any main WP, and we don't add a GPX track, the route has no georef and no associated area.

Using associated WP (which one? the first one? a centroid of all of them?) as default route geom when no main WP is set would make sense indeed.

> Then, the route can't be found by the search tool when we filter on the map extend (= default map config).

That's a consistent behaviour :) That's the reason why the "don't use the map as filter" checkbox has been added => in order to find document even when they have no geom (useful for images for instance).

**Comment by fbunoz** [comment] 2016-11-28 10:22
> That's a consistent behaviour :)

Yes, but all outings and routes should have a georef, since a route must be associated to at least one WP, whose the georef is mandatory, and an outing must be associated at least to one route.

> Using associated WP (which one? the first one? a centroid of all of them?) as default route geom when no main WP is set would make sense indeed.

We can use the higher WP, or a centroid of all associated WP. I don't know what it is easier.

**Comment by asaunier** [comment] 2016-11-28 10:26
> Yes, but all outings and routes should have a georef, since a route must be associated to at least one WP, whose the georef is mandatory, and an outing must be associated at least to one route.

Right!
But it's something different. What I meant was there is no problem with the advanced search. So it's no use mentioning it, it makes thing more confusing. The problem is only that some routes or outings have no default geometries (which is what the issue title says). :)

**Comment by desnoes** [comment] 2017-01-08 08:26
@fbunoz @asaunier : is this issue still relevant. Normally, there is a main WP by default, so this issue not longer exists, no ?

**Comment by fbunoz** [comment] 2017-01-08 14:31
I created a raid without main WP neither GPX track : the route has a georef (the centroid of all associated WP), and it is associated to some areas.
http://www.demov6.camptocamp.org/routes/828336/fr/traversee-grenboble-greater-lausanne-a-cloche-pied
I tested route creation from topoguide page, and from WP page : it works in both case.
I don't know who has fixed this issue: is it wanted or not ?

**Comment by desnoes** [comment] 2017-01-14 15:22
@asaunier: could you confirm we can close this issue ?

**Comment by asaunier** [comment] 2017-01-16 16:15
@desnoes I don't know. @fbunoz seems to say it's OK. If people have tested this case in the demo and think it's OK, feel free to close the issue.

**Closed** 2017-01-16 16:39 UTC
Labels: Guidebook
