### ISSUE TITLE
Quality attribute in documents (1d)

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#307] opened 2016-04-13 14:53 UTC
- [x] Add the quality attribute in editing forms
- [x] Show the attribute in detailed view and list pages?
- [ ] Outings with poor quality are not shown in the list pages or on the home page feed

**Comment by asaunier** [comment] 2016-04-13 15:06
Duplicate of https://github.com/c2corg/v6_ui/issues/272 ?

**Comment by fjacon** [comment] 2016-04-13 15:08
sorry, closing

**Comment by loicperrin** [comment] 2016-10-20 21:45
Reopen for this item:

- [ ] Outings with poor quality are not shown in the list pages or on the home page feed

**Comment by asaunier** [comment] 2016-10-20 22:10
> Outings with poor quality are not shown in the list pages

That doesn't make sense. The advanced search pages has a "quality" filter for this needed. So nothing to do for list pages.

Home page feed, see https://github.com/c2corg/v6_api/issues/432
But honestly, for me it's not that easy!

**Comment by loicperrin** [comment] 2016-10-20 22:34
> That doesn't make sense. The advanced search pages has a "quality" filter for this needed. So nothing to do for list pages.

OK

**Closed** 2016-10-20 22:35 UTC
