### ISSUE TITLE
Image titles are not shown on Firefox with pswp

### ISSUE THREAD

**Issue by lbesson** [c2corg/v6_ui#1182] opened 2016-12-10 16:08 UTC
This works on Chrome

**Comment by brunobesson** [comment] 2016-12-11 09:24
I'd this related to https://forum.camptocamp.org/t/donnees-iptc-des-images-non-prises-en-compte/173517/6?u=b_b  our should I open another issue?

**Comment by lbesson** [comment] 2016-12-11 12:51
I don't think so

**Comment by brunobesson** [comment] 2016-12-13 09:16
I don't understand the issue then. Could you show me an example?

**Comment by brunobesson** [comment] 2016-12-13 09:19
>I don't think so

I opened #1198 for this.

**Comment by lbesson** [comment] 2016-12-13 09:22
https://www.camptocamp.org/outings/818960/fr/cerro-copatanca-sommet-n-traversee-arete-nw-greatergreater-arete-sw

click on the pictures

On chrome desktop the image title is displayed at the bottom when you click
the image. It doesn't work with firefox or chrome mobile. Thus making it
very hard to read the image caption

**Comment by brunobesson** [comment] 2016-12-13 09:28
>On chrome desktop the image title is displayed at the bottom when you click
the image.

OK now I understand. The fact is on Chrome 50, it isn't showing either, so I wasn't aware of this possibility. 

#1198 is thus related to this issue. @asaunier should we merge or close one of the issues?

**Comment by brunobesson** [comment] 2016-12-14 21:14
I have spent 2 hours trying to understand why the image is overrlapping the title `<h2>` tag on FF, but without success :sob: 
Does someone knows the status of this feature on IE11 or Edge?

**Comment by brunobesson** [comment] 2016-12-14 21:23
Anyway, one should look deeper into it, because I have the impression some things are not done the right way: the view image / edit image / info buttons + the caption are placed inside the `.pswp_item` elements but
* the caption should be put in the `.pwsp_caption` tag
* the additional buttons should be added next to the other default ones (fullscreen + close) and appear and disappear the same way.

**Comment by flob38** [comment] 2016-12-19 18:03
@brunobesson 
If the `.photoswipe-image-container` is not `display : flex` : 
- Firefox / Chrome : hover on the image shows the title
- IE : the title is always displayed

But I don't know why :-)

**Comment by flob38** [comment] 2016-12-19 21:55
`.photoswipe-image-container` : 
removing `align-items: center` and `adding flex-direction: column` seem to work.

**Comment by brunobesson** [comment] 2016-12-20 08:30
@flob38 indeed! could you propose a PR for this?

**Comment by ginold** [comment] 2016-12-20 08:47
wow, that's unexpected... I don't understand why ;p but ok! nice finding.

**Comment by desnoes** [comment] 2016-12-23 07:04
@lbesson, @brunobesson , @flob38 : could you test if it is fixed on the demo site ?

**Comment by brunobesson** [comment] 2016-12-23 07:34
Yes the issue is fixed.
Although this doesn't solve the problem on mobile, because title is only shown when hovering. But we should open another issue for this.

**Closed by brunobesson** 2016-12-23 07:34 UTC
Labels: bug, fixed and ready for testing
