### ISSUE TITLE
Demo server - feed data loading problem

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#790] opened 2016-10-25 08:23 UTC
As F. said on meeting - now there is error with feed http://c2corgv6.demo-camptocamp.com/ (F. - Firefox, me Chromium) 

For me the error is:
![image](https://cloud.githubusercontent.com/assets/6165660/19678077/88de05ec-9a9c-11e6-92b9-51ff03a8b4c7.png)

![image](https://cloud.githubusercontent.com/assets/6165660/19678063/8032cd06-9a9c-11e6-8da1-82752a21948b.png)

"
GET http://c2corgv6-api.demo-camptocamp.com/personal-feed?pl=en 

XMLHttpRequest cannot load http://c2corgv6-api.demo-camptocamp.com/personal-feed?pl=en. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://c2corgv6.demo-camptocamp.com' is therefore not allowed access. The response had HTTP status code 401.
"

**Comment by asaunier** [comment] 2016-10-25 08:37
The Apache logs say:

> redis.exceptions.ResponseError: Error running script (call to f_5688a2541c9edd77746bcd2385e65ff3639a664f): @user_script:2: @user_script: 2: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

It's probably a memory problem again because of the Discourse instance. I will shut it down.

**Comment by tsauerwein** [comment] 2016-10-25 08:40
@arnaud-morvan said something that there is not enough disk space on this server?

**Comment by asaunier** [comment] 2016-10-25 08:41
@tsauerwein I think he was talking about the exoscale demo, not the dev server.

**Comment by asaunier** [comment] 2016-10-25 08:42
Discourse has been shut down on the dev server and the feed seems OK now.

**Comment by dkocich** [comment] 2016-10-25 08:45
I have this problem on localhost also.
![image](https://cloud.githubusercontent.com/assets/6165660/19678921/10291dfe-9aa0-11e6-84c5-f6aec58ddd7d.png)

Are you sure it is not related to this?
http://stackoverflow.com/questions/29547003/angularjs-no-access-control-allow-origin-header-is-present-on-the-requested-r
https://www.w3.org/wiki/CORS_Enabled#For_Apache

**Comment by tsauerwein** [comment] 2016-10-25 10:13
> Are you sure it is not related to this?

The CORS preflight request failed, because the main request failed. CORS should be set up correctly.

**Comment by fjacon** [comment] 2016-10-27 09:31
can we close this ticket ?
The feed seems ok now

**Comment by asaunier** [comment] 2016-11-03 11:24
I don't observe this problem on any instance (mine + the demos) => closing. Please reopen if the problem can be reproduced.

**Closed by asaunier** 2016-11-03 11:24 UTC
