### ISSUE TITLE
Issue on Prod site - Comments on outings cannot be added

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#1128] opened 2016-12-07 14:17 UTC
I use the following outing
https://www.camptocamp.org/outings/471244/fr/la-bastille-guy-pape

I try to add a comment, I get the following error message : **Topic already exists : 471244_fr**

Next test, outing https://forum.camptocamp.org/t/660519-fr/173223. I have been able to add a comment but don't see the comment linked to the outing.

**Comment by asaunier** [comment] 2016-12-07 14:21
Duplicate of this issue @desnoes has created a bit earlier: https://github.com/c2corg/v6_ui/issues/1125

**Closed by asaunier** 2016-12-07 14:21 UTC
