### ISSUE TITLE
Sitemap 501 error

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1155] opened 2016-12-08 13:43 UTC
https://www.camptocamp.org/sitemaps/m/0.xml returns a 501 error.

What does `m` stands for?

**Comment by tsauerwein** [comment] 2016-12-08 13:44
Closing as a duplicate of https://github.com/c2corg/v6_ui/issues/1154

> What does m stands for?

Map.

**Comment by brunobesson** [comment] 2016-12-08 13:45
I was going to close this duplicate, your issue was created while I was editing mine!

**Closed by tsauerwein** 2016-12-08 13:44 UTC
