### ISSUE TITLE
Problems with image uploading

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#929] opened 2016-11-18 16:22 UTC
When i try to upload an image, the upload counter (percentage) goes up to 99% and then go back to 10% and restart. This process loops endlessly and the image is never uploaded. I use FF with version 49.0.2.

**Comment by mgerbaux** [comment] 2016-11-19 11:46
Same issue (using FF or Chromium)
Images with small weight (100-200 ko) can be uploaded, larger(about 1.5Mo) not (with @asaunier poor wifi connection).

**Comment by ginold** [comment] 2016-11-21 16:00
I tried to upload big images (one 2.5Mo and one 5.1Mo) simultaneously, on FF (49.0.2) and Chrome with no issues. 

If there is a poor connection - that is nothing special. It happens to me to load pictures on facebook from my phone with bad connection and the loading sometimes never reaches the end...

**Comment by asaunier** [comment] 2016-11-21 23:17
I have tested to upload  3.7MB image from my place, with a standard connection (actually a pretty low one). It failed all the times (4 times) I have tried with alert  "Error while uploading the image: Timeout": after about 60 seconds the upload seems to be interrupted if it's not over.

At least twice I have noticed the progress bar went until ~60% then fell back to 10% before growing again and finally being interrupted by the time out.

**Comment by ginold** [comment] 2016-11-22 08:46
I retested with the 5MB image with throttling in google (Regular 2G - 50kb/s) - it took maybe 5 minutes but it made it - but only on my instance, not on demo-c2corg! 

I'm not sure to be able to answer to this issue. @arnaud-morvan, does this problem says something to you ?

**Comment by mgerbaux** [comment] 2016-11-23 20:21
I try with another PC (49.0.2 /linux) : same issue to upload images (about 1.5Mo, compliant to V5 spec and already uploaded on V5)
My connection is at the moment about 1Mb/s for uploading

**Comment by fbunoz** [comment] 2016-11-23 21:30
I tried uploading a 5Mb image : it seems that it is uploaded without resizing (firebug notes 5Mb uploaded data).
In these conditions, it is normal the server doesn't accept the file.

**Comment by arnaud-morvan** [comment] 2016-11-24 14:36
Sorry, but I don't really know how to solve this.
Maybe we could increase the image backend timeout, gunicorn should have an option for that.

**Comment by mgerbaux** [comment] 2016-11-24 14:44
What are the specificities of the images (size, weight) theoritecally accepted by the server ?

**Comment by arnaud-morvan** [comment] 2016-11-24 14:47
No restriction on image properties, the problem should come from some timeout with the request.

**Comment by asaunier** [comment] 2016-11-24 14:55
Is the problem limited to FF? If not we should update the title.

In addition the problem reported initially by @desnoes seems to be different (no timeout, but an endless upload). Is it really the same problem?

**Comment by desnoes** [comment] 2016-11-24 15:07
I will check tonight if a timeout occurs. When i observed the problem i stopped the process before the timeout.

----- Mail original -----
De: "Alex Saunier" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 24 Novembre 2016 15:55:37
Objet: Re: [c2corg/v6_ui] Impossible to upload an image (FF) (#929)



Is the problem limited to FF? If not we should update the title. 

In addition the problem reported initially by @desnoes seems to be different (no timeout, but an endless upload). Is it really the same problem?

**Comment by desnoes** [comment] 2016-11-24 15:16
I've observed a similar problem with Chrome and an image of 4.4Mo. The upload process restart once and it took a lot of time to upload but it worked at the end. 

----- Mail original -----
De: "mathieu desnoes" <mathieu.desnoes@free.fr>
À: "c2corg/v6_ui" <reply@reply.github.com>
Cc: "Mention" <mention@noreply.github.com>, "c2corg/v6_ui" <v6_ui@noreply.github.com>
Envoyé: Jeudi 24 Novembre 2016 16:07:11
Objet: Re: [c2corg/v6_ui] Impossible to upload an image (FF) (#929)

I will check tonight if a timeout occurs. When i observed the problem i stopped the process before the timeout.

----- Mail original -----
De: "Alex Saunier" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 24 Novembre 2016 15:55:37
Objet: Re: [c2corg/v6_ui] Impossible to upload an image (FF) (#929)



Is the problem limited to FF? If not we should update the title. 

In addition the problem reported initially by @desnoes seems to be different (no timeout, but an endless upload). Is it really the same problem?

**Comment by fbunoz** [comment] 2016-11-25 07:03
Is there a resizing process into the broweser, or the image is resized by the server ?
If it is resized by the server, there will be server overloads.

**Comment by asaunier** [comment] 2016-11-25 10:12
There is no client side resizing as for now I think. At least this point is not checked in this list https://github.com/c2corg/v6_ui/issues/164#issuecomment-204345064
@ginold could you confirm?

Image client-side resizing is supported by ng-file-upload, the angular lib we use for image uploading, see the ``ngf-resize`` directive in https://github.com/danialfarid/ng-file-upload I think.
Perhaps it could be added to https://github.com/c2corg/v6_ui/blob/a0e8a104094bdd3b2f33d2061d2f9cc83547a793/c2corg_ui/static/partials/imageuploader.html#L1-L14 ?

**Comment by stef74** [comment] 2016-11-29 10:25
When do you think this issue is fixed ?

**Comment by ginold** [comment] 2016-11-29 11:34
I confirm there is no client-side resizing as for now. 
But don't we upload the full image to the server anyway, that can be displayed after clicking on the image itself in the view-page, in full screen ? 

That's still strange, because there is no problem when uploading an image at 1kb/s on local instance, the problem only appears on the demo. There is an issue with the timeout.

**Comment by asaunier** [comment] 2016-11-29 12:00
> But don't we upload the full image to the server anyway

@fbunoz means that in v5 the uploading client checks that the image is not too big and if yes, resize it before uploading it. The server receives a resized original which is then used to create the SI/MI/BI images as usual. It seems possible to do the same thing with ng-file-upload.

**Comment by ginold** [comment] 2016-11-29 12:02
Yes, it looks like it features resizing.
And what would be considered as a "too big image" and what would be the "correct, smaller size"?

**Comment by asaunier** [comment] 2016-11-29 12:07
> what would be considered as a "too big image" and what would be the "correct, smaller size"?

@fbunoz could you please precise?

**Comment by mgerbaux** [comment] 2016-11-29 12:12
>  And what would be considered as a "too big image" and what would be the "correct, smaller size"?

We can take V5 values :  size < 8192 x 2048 px AND weight < 2 Mo

**Comment by loicperrin** [comment] 2016-11-29 23:53
I have tested with images < 1.5 Mo => OK
I have tested with images > 4 Mo => KO

**Comment by ginold** [comment] 2016-11-30 09:10
You have some poor connection guys :P 5.5Mo no problem on the demo.

**Comment by asaunier** [comment] 2016-11-30 09:27
@ginold Remember that not all users of c2corg live in cities or even have huge bandwidths :P There are also users using mobile phones.

**Comment by fjacon** [comment] 2016-11-30 12:35
@mfournier can you test and upgrade timeout

**Comment by asaunier** [comment] 2016-11-30 12:41
Client-side resizing has been moved to a dedicated issue: https://github.com/c2corg/v6_ui/issues/1046

For this issue: only increase a bit the timeout setting.

**Comment by loicperrin** [comment] 2016-12-01 22:18
I have seen something strange which can help fixing this issue: when uploading an image I see the progression bar go to 88% (for example), and suddenly, it goes down to 44%, and this occurs several times, till I get the timeout.

**Comment by asaunier** [comment] 2016-12-02 08:53
> For this issue: only increase a bit the timeout setting.

@arnaud-morvan @mfournier Is it a setting of the images backend ("S3 bucket")?

**Comment by arnaud-morvan** [comment] 2016-12-05 15:09
This should be set as a gunicorn option : gunicorn --timeout in the docker compose file CMD entry.
http://docs.gunicorn.org/en/latest/settings.html#timeout

**Comment by loicperrin** [comment] 2016-12-06 23:05
I think there is really a problem with image uploading, and not only a timer pb.
I have tried to upload a 2.7 Mo image on demo -> after 30s: timeout
If I upload the same image on Imgur, it takes less than 10s (with the same internet connection of course).
So even if the timeout is higher, it is not acceptable to wait for a long time to upload 2.7 Mo images.

Do you have investigated this:
>I have seen something strange which can help fixing this issue: when uploading an image I see the progression bar go to 88% (for example), and suddenly, it goes down to 44%, and this occurs several times, till I get the timeout.

**Comment by loicperrin** [comment] 2016-12-06 23:07
Here it takes around 30s to upload the same image:
![dsc_0380](https://cloud.githubusercontent.com/assets/19718055/20947776/0f922542-bc11-11e6-821a-5897a45c3858.JPG)

**Comment by mgerbaux** [comment] 2016-12-07 19:22
On prod server, during image uploading process, when clicking on the button "enregistrer", i get the following message : "please consult the server logs : unexpected error".
and process failed…

**Comment by loicperrin** [comment] 2016-12-07 23:40
> when clicking on the button "enregistrer", i get the following message : "please consult the server logs : unexpected error".
and process failed…

Seems to be a different pb.
I have also seen it, but before I have always error when uploading a 2 Mo image. If I resize it to 500 ko I can upload it, but I get "please consult the server logs : unexpected error" when trying to save.

**Comment by stef74** [comment] 2016-12-08 12:16
@mfournier @asaunier timeout was increased ?

**Comment by asaunier** [comment] 2016-12-08 12:21
Not yet

**Comment by arnaud-morvan** [comment] 2016-12-08 17:03
We should make tests on demo server to find the expected timeout setting.

**Comment by mfournier** [comment] 2016-12-13 12:24
So #1046 makes this difficult to reproduce now, which is a good thing in a way.

I was able to reproduce the problem by simply using `curl -v 'http://<SERVERNAME>/upload' -F "name=@largefile.jpg;filename=largefile.jpg"`, which results in these log messages:

```
{"message": "WORKER TIMEOUT (pid:17)", "levelname": "CRITICAL", "name": "gunicorn.error", "asctime": "2016-12-13 12:20:50,373", "funcName": "critical", "lineno": 238, "pathname": "/usr/local/lib/python3.4/dist-packages/gunicorn/glogging.py", "stack_info": null, "module": "glogging", "created": 1481631650.3736758, "threadName": "MainThread", "processName": "MainProcess", "getMessage": null}
{"message": "Worker exiting (pid: 17)", "levelname": "INFO", "name": "gunicorn.error", "asctime": "2016-12-13 12:20:50,375", "funcName": "info", "lineno": 247, "pathname": "/usr/local/lib/python3.4/dist-packages/gunicorn/glogging.py", "stack_info": null, "module": "glogging", "created": 1481631650.3756154, "threadName": "MainThread", "processName": "MainProcess", "getMessage": null}
{"message": "Booting worker with pid: 135", "levelname": "INFO", "name": "gunicorn.error", "asctime": "2016-12-13 12:20:50,460", "funcName": "info", "lineno": 247, "pathname": "/usr/local/lib/python3.4/dist-packages/gunicorn/glogging.py", "stack_info": null, "module": "glogging", "created": 1481631650.4600112, "threadName": "MainThread", "processName": "MainProcess", "getMessage": null}
```

This matches with the default gunicorn worker timout @arnaud-morvan mentioned.
But -1 for simply bumping the timeout value. The issue here is that uploads lock one worker during the process. Meaning the service can't handle more than $NUM_WORKERS concurrent uploads. The right solution is to switch to one of the asynchronous gunicorn worker classes.

**Comment by desnoes** [comment] 2016-12-14 10:15
I copy here the problem reported by an italian user (cf. https://forum.camptocamp.org/t/v6-vos-questions-les-reponses/173468/133?u=miko):
Image not uploaded is only 900kb, 2272 x 1704 but 300dpi, instead image uploaded is 1,2Mb, 2272 x 1704 but 180dpi. Resizing from 300dpi to 180dpi I can upload it......images are from different cameras (Canon>>>works, Nikon Coolpix>>>doesn't works)

**Comment by asaunier** [comment] 2016-12-14 10:41
@desnoes I have tested uploading both images found in the post you quote: no error. But it seems the images made available in the forum are not the original ones (400 KB each). We would need the original images to test.

**Comment by desnoes** [comment] 2016-12-14 11:56
i have asked the original images to Paolo Recalcati. How do i transfer them afterwards ? An email to you Alex ?

----- Mail original -----
De: "Alex Saunier" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mercredi 14 Décembre 2016 11:41:46
Objet: Re: [c2corg/v6_ui] Problems with image uploading (#929)



@desnoes I have tested uploading both images found in the post you quote: no error. But it seems the images made available in the forum are not the original ones (400 KB each). We would need the original images to test.

**Comment by asaunier** [comment] 2016-12-14 11:57
Perhaps you can post them in the issue.

**Comment by desnoes** [comment] 2016-12-14 13:29
@asaunier : here is the image that was not uploaded. I don't know if it is processed by Github so i also transfered the email of Paolo.

![santambrogio1 014](https://cloud.githubusercontent.com/assets/19892089/21183730/8da14bae-c209-11e6-829b-083acf3f29ef.jpg)

**Comment by asaunier** [comment] 2016-12-14 14:09
@desnoes thanks! I have been able to reproduce an error with this image when uploading it to the demo or my own instance.

The image upload works and returns a filename. But then saving the image to the API fails:
```
{"status": "error", "errors": [{"location": "body", "description": "please consult the server logs", "name": "unexpected error"}]}
```
The logs say:
```
2016-12-14 14:56:12,686 ERROR [c2corg_api.views][waitress] Unexpected error: 'images'
Traceback (most recent call last):
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    reraise(*exc_info)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 88, in tm_tween
    response = handler(request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/cornice/service.py", line 478, in wrapper
    validator(request, **args)
  File "/home/alex/v6_api/c2corg_api/views/image.py", line 78, in validate_list_image_create
    for image in request.validated['images']:
KeyError: 'images'
```
It seems that no ``images`` is then passed in the validated data here: https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/image.py#L78

No problem with another image.

I see some weird GPS data in the EXIF info of the image:
<img width="317" alt="capture d ecran 2016-12-14 a 15 07 11" src="https://cloud.githubusercontent.com/assets/1192331/21184979/1e383074-c20f-11e6-89d1-7f49e7d9183b.png">

Perhaps they make the API fail. That would explain why there is no problem with images from another camera or when the image resolution is changed (the EXIF are then probably lost).

**Comment by desnoes** [comment] 2016-12-14 21:02
Here is another image sent by ThomasR which was impossible to upload.
![img_0325](https://cloud.githubusercontent.com/assets/19892089/21200800/dea2a9c8-c248-11e6-9715-0925e6cb611a.JPG)

**Comment by loicperrin** [comment] 2016-12-14 23:24
> when the image resolution is changed (the EXIF are then probably lost).

No this is probably not the cause: 
- I have tried to upload my 4.x Mo images => errror
- after resizing => upload OK, and the EXIF is still displayed
If necessary I can send you my original images.

- [ ] another problem (maybe a dedicated issue should be created?): when uploaded, the images are not sorted by date in the document

**Comment by brunobesson** [comment] 2016-12-15 08:34
>another problem (maybe a dedicated issue should be created?)
An issue already exists, #1177

**Comment by loicperrin** [comment] 2016-12-22 10:29
It seems to be better? Yesterday I have uploaded 3 images without resizing and no error message has appeared.

**Comment by stef74** [comment] 2016-12-22 16:29
Today i havé Try to upload multiple image ... sometimes seem ok but not save button. Sometimes timeout error. The only solution is to upload file by file. On safari iOS

**Comment by mfournier** [comment] 2016-12-22 21:26
On Thu, Dec 22, 2016 at 08:29:49AM -0800, stef74 wrote:
> Today i havé Try to upload multiple image ... sometimes seem ok but not
> save button. Sometimes timeout error. The only solution is to upload file
> by file. On safari iOS 

@stef74, I change some settings on demov6 a few minutes ago, which will
hopefully help with this issue.

Are you able to re-test the "upload multiple images at once scenario" ?
Thanks !

**Comment by brunobesson** [comment] 2016-12-22 21:31
I just tested at home with 4 images > 3.5Mo and it worked, but I haven't encountered the problem yet (didn't test it) and it's with a correct connection. Other tests are needed. @stef74 is on holiday, it's a perfect situation for these tests :wink:

**Comment by asaunier** [comment] 2016-12-28 00:10
> Today i havé Try to upload multiple image ... sometimes seem ok but not save button. Sometimes timeout error. The only solution is to upload file by file. On safari iOS

I have realized that the client-side resizing was only enabled for the initial upload panel, not for the secondary panel that appears after a first set of images have been dragged => there was no client resizing when dragging images in the panel in several times. Should be fixed by https://github.com/c2corg/v6_ui/pull/1282

**Comment by asaunier** [comment] 2017-01-01 15:38
A problem with the image uploader is that it tries to upload all submitted images at the same time. Which is a non-sense: if too many images are uploaded at the same time, the bandwidth might be not enough to send all of them in a reasonable amount of time, thus causing timeout errors.

It would make more sense that the only 1 or 2 images are uploaded at the same time and that the uploader starts uploading additional images when the latter uploads are done.

By the way I have realized that when many images are uploaded in the same batch, the API request to save the associated data (not the files!) takes a while... Perhaps there are things to optimize in the API to reduce the delay needed to save those data?

**Comment by loicperrin** [comment] 2017-01-01 21:37
Juste now I have problems to upload images:
- I have tried to drag and drop 6 images: after waiting a little time, only 2 images appear, but not the "save" button. I try to add another image => timeout
- I have tried to drag and drop juste 1 image => OK
- I have tried to drag and drop juste 2 images => OK
- I have tried to drag and drop juste 3 images => OK

**Comment by loicperrin** [comment] 2017-01-01 21:57
- another trial with 3 images => KO (the 3rd image and the "save" button do not appear)
- 2 images => OK

**Comment by asaunier** [comment] 2017-01-11 14:10
I don't know if an infra task remains to be done about this issue? @mfournier what do you think?

Since the issue is getting a bit too big and hard to read, I have created 2 "spun off" issues that should no longer be considered here:
* Images uploader should upload images sequentially #1340
* Error validating some uploaded images c2corg/v6_api#600

**Comment by stef74** [comment] 2017-01-13 09:05
@mfournier infra task on this topic ? if not I close

**Comment by desnoes** [comment] 2017-01-13 09:17
I think we must perform some tests before closing the issue.

**Comment by mfournier** [comment] 2017-01-13 13:09
Yes, my impression is that part of the problem lies in the worker model used:

> if too many images are uploaded at the same time, the bandwidth might be not enough to send all of them in a reasonable amount of time, thus causing timeout errors.

We have a finite numer of workers available on the server side, which are working in a synchronous way. If several users with limited bandwith upload image simultaneously, all the workers will get locked, waiting on TCP packets which arrive only very slowly.
The solution to *this specific problem* is switch to one of the asynchronous worker models gunicorn offers. cf 2d729062 and the URL linked in this commit's comment.

**Comment by desnoes** [comment] 2017-01-18 21:35
For testing, a new image that was not uploaded successfully.
![dscn7512](https://cloud.githubusercontent.com/assets/19892089/22083904/4216e80c-ddce-11e6-9fd7-5751277b0e6f.JPG)

**Comment by asaunier** [comment] 2017-01-19 09:38
@desnoes Thanks, again a problem with the GPS coordinates that are not correctly formatted when sent to the API:
![capture du 2017-01-19 10-32-26](https://cloud.githubusercontent.com/assets/1192331/22101209/b7fe8e3a-de32-11e6-8f0e-4de8e10daa19.png)

=> same problem described here: https://github.com/c2corg/v6_api/issues/600 and here https://github.com/c2corg/v6_ui/issues/1341#issuecomment-271899528

**Comment by asaunier** [comment] 2017-01-24 11:54
@desnoes Can we close this issue?

Remaining related problems are described in dedicated issues:
https://github.com/c2corg/v6_ui/issues/1340

Some have been fixed and awaiting to go to demo/prod:
https://github.com/c2corg/v6_ui/issues/1341
https://github.com/c2corg/v6_ui/issues/1176
https://github.com/c2corg/v6_api/issues/600

**Closed** 2017-01-24 15:07 UTC
Labels: blocking, Images, server / infra
