### ISSUE TITLE
Documents display: problem with carriage return

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#494] opened 2016-07-14 16:16 UTC
If there is carriage return (CR) in text fields, when the text is displayed, there is no more CR.
See for example: outings/736968/fr
In "Commentaires Personnels": "A refaire" should be displayed on a 2nd line and "Photos à venir" in a 3rd line.
Same problem with fields Meteo, conditions,...

**Comment by asaunier** [comment] 2016-07-18 06:40
I have updated the title of the issue because it is probably not restricted to outings.
The issue is most likely related to the bbcode/markdown parsers, see https://github.com/c2corg/v6_ui/issues/131

**Comment by asaunier** [comment] 2016-09-28 14:34
Closing this issue because duplicate of https://github.com/c2corg/v6_ui/issues/420 which itself is closed because part of https://github.com/c2corg/v6_ui/issues/131

**Closed by asaunier** 2016-09-28 14:34 UTC
Labels: bug, Guidebook
