### ISSUE TITLE
waypoints icons are too stacked on the map

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#338] opened 2016-04-29 09:35 UTC
On the list view, the waypoint icons are on top one another which is not readable. The reason for this is the extent of showed waypoints - there are for example 15 wps in europe and one in china. 

I don't know it there is an easy way to filter that on the API side and show only wps that are close enough one to another, but in the UI we could use clustering.
Or will this be resolved in the future when we decide to filter the results through map extent? But as from now, the extent is based on the returned waypoints.

**Comment by asaunier** [comment] 2016-05-18 13:49
Maybe related to https://github.com/c2corg/v6_ui/issues/285 ?

**Comment by tsauerwein** [comment] 2016-05-19 06:36
When clicking on the map, we could show a popup with a list of features at that point.

**Comment by asaunier** [comment] 2016-05-19 07:55
Would it actually solve the current issue (too many icons at the same place)? Or do you mean we could have a cluster layout + a popup listing the object at this point?

**Comment by asaunier** [comment] 2016-06-22 09:22
Duplicate of https://github.com/c2corg/v6_ui/issues/285

**Closed by asaunier** 2016-06-22 09:22 UTC
Labels: Map
