### ISSUE TITLE
Comments in topoguide

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1216] opened 2016-12-14 14:25 UTC
I was wondering why there were so many discussions started in comments without replies. At first glance, I thought a discussion is created for each and every outing.
But after further investigation the bahaviour seems different. Can you confirm?
* there is no discussion by default
* when one clicks on first comment button and opens a page in discourse, a discussion is created, with admin being the first poster, adding a link to the outing

There is a problem though: when you click on the link to add a comment but finally don't, the discussion remains. The styling in the outing is bad:

![toto2](https://cloud.githubusercontent.com/assets/2234024/21185571/7d1fae6c-c211-11e6-9019-47b6434b5be1.png)

Are there any plans concerning this?

**Comment by asaunier** [comment] 2016-12-14 14:45
I think such comments are created when someone clicks on the "make a comment" button. But then in many cases the popup is blocked (popup blocker), nothing appears: if the user does not figure out he should reload the page, he gives up adding a comment.

**Comment by fbunoz** [comment] 2016-12-14 15:43
One point to improve : decrease the number of response of 1 to give the exact user responses without counting the system post.

**Comment by asaunier** [comment] 2016-12-23 08:37
@arnaud-morvan Just curious why a new page must be added to create a new comment topic or make an answer? Is it enforced by the Discourse API or is this a choice to keep the commented document open?

I was wondering if we could not rather open Discourse in the same tab than the current document. This way no blocked window issue. The original document is then still reachable using the link in the first post (perhaps some styling could be applied to make it more obvious, eg. a colored background, bigger font etc.?) and if the user really want to open a new tab, it should be possible to shift+click or middle-click the comment button?

**Comment by arnaud-morvan** [comment] 2017-01-03 14:33
Yes it seems possible, take a look here:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/viewdetails.js#L341

It seems we could replace ``window.open(url);`` by ``window.location = url;``.

**Comment by asaunier** [comment] 2017-01-04 14:36
@arnaud-morvan thanks!

I have made the change with PR #1296

**Comment by desnoes** [comment] 2017-01-05 06:41
I have tried to comment the following document: http://www.demov6.camptocamp.org/routes/828297/fr/caroux-tour-verte-test-iti-avc-wp-principal
It is not working.

![comment topoguide](https://cloud.githubusercontent.com/assets/19892089/21671242/53ebb56c-d31a-11e6-9233-013466dd5831.jpg)

**Comment by stef74** [comment] 2017-01-05 07:21
But it's blocking or not ? ( if you move in production user can comment ?)

**Comment by brunobesson** [comment] 2017-01-05 07:45
Well:

* clicking on the link to start a discussion is OK
* clicking on the link to continue a discussion is KO
* the forum is non functional (because of CSS problem in the demo?), but this is not related to this issue (although it should be investigated if this behaviour would be reproduced on the server)

We can close the issue if you like, but it is only partially solved, another issue should then be created. As the fix sems to be pretty straightforward, I would recommend fixing it first.

**Comment by AlexisDemongeot** [comment] 2017-01-05 09:06
What's works : 
 - initiate a discussion is OK.
 - continue a discussion is always OK, even if you come back canceling the post and finally decide to open a post by clicking on the link to continue a discussion.

What's not work : 
 - in cas case you tryed to open a discussion and come back and finaly go on : it seems to works, you don't have anymore : 
![image](https://cloud.githubusercontent.com/assets/24522280/21674508/530e311a-d32e-11e6-8982-c08a1aac9d12.png)

But still remains : 
![image](https://cloud.githubusercontent.com/assets/24522280/21674539/68bc87b4-d32e-11e6-96d9-38595c7ec0f7.png)

**Comment by arnaud-morvan** [comment] 2017-01-05 09:13
We have disk space problem on the demo forum server.
This cause the server to be completely unavailable, or only css files for today.
I've disabled the discourse automatic backup system on demov6, this should solve the problem.

Apart from this, everything seems to work fine for me.

I've run a full rebuild of discourse, to get a fresh new container, without backup files, this will be ready in sme minutes.

**Comment by stef74** [comment] 2017-01-05 10:10
@brunobesson @AlexisDemongeot could you retry. for me forum is ok now ... but not undestand clearing the objectif of this issue (currently it open discourse in new page for me ...)

**Comment by brunobesson** [comment] 2017-01-05 10:13
The goal of this issue is not to open a new tab from topoguide when commenting an outing.
It has been fixed when starting a new discussion, but not when continuing an existing one.

As for @AlexisDemongeot feedback with "Topic already exists", this should be another issue IMHO.

**Comment by arnaud-morvan** [comment] 2017-01-05 12:31
Note that the "Continue the discussion" button is served in an iframe by discourse, this come from Discourse and I don't see any option to change that behavior.

**Comment by stef74** [comment] 2017-01-13 08:28
@brunobesson @asaunier we have to do anything ... my understanding is not (we can but very low prio)

**Comment by brunobesson** [comment] 2017-01-13 08:31
Yes we do:

* @asaunier made the discussion open in the same tab when starting a new one, but not when continuing one
* there is a problem when someone "starts" a discussion but do not post anything then (which was the original issue I reported). I think this should be handled, but you could add low prio label.

**Comment by stef74** [comment] 2017-01-13 08:47
ok need to be done by SA ?

**Comment by brunobesson** [comment] 2017-01-13 08:58
The first point, yes. For the rest, I don't deal with such subjects :wink:

**Comment by AlexisDemongeot** [comment] 2017-01-13 09:32
@stef74 : 

Retrying. It's tehe same comportement for me.
Version of Chrome : 
![image](https://cloud.githubusercontent.com/assets/24522280/21924893/57dea898-d97b-11e6-845c-215e63751e74.png)

If you clic on initiating a discussion, then come back, and try to initiate a conversation, you've still : 
![image](https://cloud.githubusercontent.com/assets/24522280/21924883/48ea9d7e-d97b-11e6-9aa6-47c7d661b93c.png)

If you refresh the page, you 'll have : 
![image](https://cloud.githubusercontent.com/assets/24522280/21924963/9d626328-d97b-11e6-9b24-8d8eb3c05015.png)

**Comment by arnaud-morvan** [comment] 2017-01-13 12:48
When using the browser back button, the page should be taken from the cache.
But when clicking on the create discussion button, the page should be updated with discourse embeded iframe before navigating to discourse topic.
I will investigate.

**Comment by arnaud-morvan** [comment] 2017-01-13 15:17
After investigation: the browser take the page from it's cache without DOM changes made by javascript.
So the original page is shown, in the state before the topic was created.
This is a browser behavior that which can be considered as a feature (you go back in history).

I do not find simple way to override this: 
* when the page come from the browser cache, I have no way to know that the topic exists.
* when I get the error, I do not have the topic_id in the error message.

Note that in the API error message, we can change the name property value (actually the topic title) by the topic_id. After that we could show the topic iframe when we get the error 'Topic already exists' on the client side.

**Comment by AlexisDemongeot** [comment] 2017-01-13 15:29
@arnaud-morvan Ok, if the message is human understandable, it will be easier to be accepted.

**Comment by arnaud-morvan** [comment] 2017-01-13 16:00
I do not see any error message translation on the api side.
@tsauerwein, @asaunier : Is it possible to translate error messages from API ? Where ?

**Comment by fbunoz** [comment] 2017-01-13 17:05
> Changing the name topic-id by topic_title can be interessting.

Arnaud talken about forum topic title and ID : 

- topic title = doc ID + doc language => 821546_fr
- topic ID = discourse topic ID => 175423

It could interesting to have the doc title in the topic title, but it is another problem.

**Comment by arnaud-morvan** [comment] 2017-01-16 10:49
I've managed to show the existing topic in the document page, after showing the error "Topic already exists".
IHMO this is a convenient solution from a user point of view. The user can process.

**Comment by AlexisDemongeot** [comment] 2017-01-16 11:00
Is it active on the demo site ? 

I think, it's a little bit confusing but, the user will understand quickly. Thanks.

**Comment by arnaud-morvan** [comment] 2017-01-16 11:54
Not yet on demo, waiting for review for the moment.

**Comment by stef74** [comment] 2017-02-21 08:43
@arnaud-morvan what is the status ?

**Comment by arnaud-morvan** [comment] 2017-02-21 10:33
I've forgot to update the labels on this ticket, but this should be on production for now. So when you've created the comments topic in a document, if you click another time on the button, the comments are shown in the topoguide document.

**Comment by desnoes** [comment] 2017-02-21 20:49
@brunobesson @AlexisDemongeot : could you test ?

**Comment by brunobesson** [comment] 2017-02-22 08:45
Nope. Discourse is not working on demo.

**Comment by desnoes** [comment] 2017-03-08 20:19
@brunobesson @AlexisDemongeot : It seems to work.  could you test ?

**Comment by desnoes** [comment] 2017-03-13 07:03
I still have the message 'Topic alredy exists'.
@brunobesson @AlexisDemongeot @fbunoz : is it a normal behavior ? is this issue fixed ?

**Comment by AlexisDemongeot** [comment] 2017-03-13 07:35
The issue is not fixed. The problem come from page not refreshed when coming back on the page. If you refresh it it's correct.

**Comment by arnaud-morvan** [comment] 2017-03-13 09:06
Yes the message still appear, but after that, the button should be replaced by the discourse embeded iframe.

**Comment by desnoes** [comment] 2017-03-13 10:28
I did the following test: click several times on 'post the first comment' and each time i've got the message 'Topic already exists' => F5 => Discourse iframe with the button 'démarrer la discussion'. Is it the expected beahvior ?

The user must either click on F5 or leave the document. Then , when he upload the document again, he is able to post his message. Is it possible to modify the message 'Topic already exists' at least to inform the user on how to proceed ?

**Comment by arnaud-morvan** [comment] 2017-03-13 12:12
Indeed, there was an error here after closure compiling. I put back the ticket in "ready for demo" state.
I've fixed it. When the error message is shown, the button is replaced by the discourse embeded iframe. No more need to refresh the page manually.

**Comment by desnoes** [comment] 2017-03-13 12:19
ok thanks @arnaud-morvan.

**Comment by desnoes** [comment] 2017-03-19 16:05
fixed on demo

**Closed** 2017-03-19 16:05 UTC
Labels: extra, fixed and ready for testing
