### ISSUE TITLE
New missing translations in Transifex

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#705] opened 2016-10-07 09:10 UTC
The following translations are missing in Transifex:
- [x] Left-side menu: "Community" is not translatable:

![image1](https://cloud.githubusercontent.com/assets/20488365/19180918/b3a4fff6-8c69-11e6-9301-a942d174421f.png)
- [x] WP creation: http://c2corgv6.demo-camptocamp.com/waypoints/add, I select "access" type.

The criteria "Accessibilité en transports en commun" and "Stationnement payant" have common parameters, whereas I think they should both have own and independant ones. For example "seasonal" should be translated by "service saisonnier" in "Accessibilité" and only "saisonnier" in "Stationnement":

![image2](https://cloud.githubusercontent.com/assets/20488365/19181159/687cfab8-8c6b-11e6-9630-f76cafc3b3f9.png)

![image3](https://cloud.githubusercontent.com/assets/20488365/19181161/6aee0418-8c6b-11e6-9ac9-50a39a4bda5a.png)

Same for answer "no".
- [x] WP creation: in case of type "site d'escalade", "sae", "produits locaux" or "station meteo":

Title "Types & styles" is not translated in Transifex. There is another field "Types & styles", but this one is missing.

![image4](https://cloud.githubusercontent.com/assets/20488365/19181334/b49aebac-8c6c-11e6-9cac-b61243b82aa1.png)
- [x] WP, route, outing display (all types), "Commentaires" area:

Field "No thread yet ?" is missing in Transifex

![image6](https://cloud.githubusercontent.com/assets/20488365/19181548/216659be-8c6e-11e6-9f92-4d91deb5486c.png)
- [x] WP display: http://c2corgv6.demo-camptocamp.com/waypoints/726442/fr/pont-de-giers

Field "Associated waypoint_children" is not translatable:

![image7](https://cloud.githubusercontent.com/assets/20488365/19181820/d3eada6e-8c6f-11e6-8e11-ad5fc022da11.png)
- [x] Outing creation (any activity), "Accès & refuge/cabane": parameters for "Fréquentation", "Remontées mécaniques", "Refuge" and "Conditions de l'accès" have been translated in Transifex, but we cannot see those translations in french:

![image10](https://cloud.githubusercontent.com/assets/20488365/19184379/160b28ce-8c7d-11e6-9bbd-e2994ceac5ad.png)
- [x] Outing creation ("ski, surf", "Neige, glace et mixte", "Rocher haute montagne", "Cascade de glace", "Raquette" ): field "Evaluation des conditions": parameters are translated in Tansifex but not displayed in french:

![image11](https://cloud.githubusercontent.com/assets/20488365/19184451/818803e2-8c7d-11e6-92a5-50be39e05328.png)
- [x] Outing creation ("ski", ): criteria "Qualité de la neige" and "Quantité de neige" do not have their own answers. Some are common with public transportation criteria, but translations are different:

![image12](https://cloud.githubusercontent.com/assets/20488365/19184505/cb52c034-8c7d-11e6-8210-85c3c7e893ab.png)

The 5 answers should be linked with those criteria only.
- [x] Route creation: title "Activités & types" is not translatable (and should be replaced by "Activités" only):

![image9](https://cloud.githubusercontent.com/assets/20488365/19182472/9da486fe-8c73-11e6-8d88-cde4bd8eba33.png)
- [x] When changing image type, in image editing form, from collaborative to personal, the error message is not translated:

![image1](https://cloud.githubusercontent.com/assets/20488365/19625458/5e70ac1c-9919-11e6-8b44-acef5c008969.png)
- [x] From the "My preferences" page of my account, I select some areas. Once chosen, the string "admin limits" is not translated:

![image2](https://cloud.githubusercontent.com/assets/20488365/19625657/f94f8fe6-991e-11e6-9069-568dcf2b3b03.png)

**Comment by ginold** [comment] 2016-10-11 13:12
also: https://github.com/c2corg/v6_ui/issues/719

**Comment by tsauerwein** [comment] 2016-10-18 13:46
* [ ] On mobile: The text "heights" in the information block does not start with capital letters when the language is "en". See screenshot here: https://github.com/c2corg/v6_ui/issues/747

**Comment by shortoland** [comment] 2016-10-18 13:54
@tsauerwein Same pb on desktop. I have modified the transation in Transifex. I think there are many problems like this with all languages. They might be solved latter, once all translations will be completed.

**Comment by asaunier** [comment] 2016-10-26 08:32
Several mis-translations reported above are caused by list values that are the same for several attributes in the source code but are translated differently. For instance:

* [ ] https://github.com/c2corg/v6_ui/issues/792 
``glacier`` is used for 2 sets of attribute values:
 * ``glacier_gear_types`` => https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L298
 * ``route_configuration_types`` => https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L310
The translation is shared between those 2 values.
Since the translation should not be the same, the original strings should not be the same in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py 

* [ ] https://github.com/c2corg/v6_ui/issues/797
``good`` is used as a value of
 * ``quality`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L601
 * ``public_transportation_ratings`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L107
 * ``condition_ratings`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L529

**Comment by asaunier** [comment] 2016-10-27 00:05
@shortoland 

> The criteria "Accessibilité en transports en commun" and "Stationnement payant" have common parameters, whereas I think they should both have own and independant ones. For example "seasonal" should be translated by "service saisonnier" in "Accessibilité" and only "saisonnier" in "Stationnement":

OK I'm renaming all the "service" values to change "seasonal" to "seasonal service", "no" to "no service" etc. Those strings will have to be retranslated in Transifex when the PR (changes) are merged.

> Title "Types & styles" is not translated in Transifex.

Actually it is. But it's not correctly understood by the tool we use to translate the UI in browsers.
It seems ``&`` is not accepted. I have changed "Types & styles" to "Types and styles".
By the way "Informations" is not a relevant french translation for this string (all other sections contain "informations" too), please stick to "Types and styles". We can also change this string to another if you can think of a better one.

> There is another field "Types & styles"

Could you tell me where?

I think I have also fixed the other points.
Some fixes require to change the translated strings, therefore to retranslate them in Transifex.
See https://github.com/c2corg/v6_common/commit/a154635c76b375ef2f6915ae034c409c4c6c0070

You have to make sure that the translations in Transifex are consistent with the change above. For instance "good" should be translated to "bonnes" (condition_ratings), not to "service régulier". The later is now the translation of "good service".

**Comment by loicperrin** [comment] 2016-11-04 21:57
- [ ] in outing (both edition and mode), "état glacier" cannot be translated
- [ ] in outing avalanche_info should be used instead of "avalanches" title in display mode (it is OK in edition mode)
- [ ] in outing condition_level is used in edition mode and conditions_level is used in diplay mode ; only one should be used in both modes

One question: are the items used for "état glacier" (facile/possible/difficile/impossible) used in another field? If not, we could change the translation to (bouché - passage sans problème/....).

**Comment by asaunier** [comment] 2016-11-05 12:45
> in outing (both edition and mode), "état glacier" cannot be translated

?
This is already a translation (there is no string in French in the code). If you change the UI to italian for instance, this becomes "Ghiacciaio".

It's rather a translation issue, to be fixed in Transifex.

> One question: are the items used for "état glacier" (facile/possible/difficile/impossible) used in another field? If not, we could change the translation to (bouché - passage sans problème/....).

Those values https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L535-L540 seem not to be used for another attribute. So it should be safe to change the translations in Transifex.

> in outing avalanche_info should be used instead of "avalanches" title in display mode (it is OK in edition mode)

Actually, the "display" page uses the correct title (the attribute is indeed "avalanches"). The problem is in the editing form that uses "avalanches_info" whereas this string is used nowhere else and is not related to an attribute.
I will make the change in the editing form. @shortoland The downside is that the translations for this title will be lost (but I think it's worth fixing those inconsistencies). 

Anyway I think those avalanche data are not correctly placed/grouped in the detail view page (display). See my comment here: https://github.com/c2corg/v6_ui/issues/449#issuecomment-258607000

> in outing condition_level is used in edition mode and conditions_level is used in diplay mode ; only one should be used in both modes

You're right! Thanks for noticing. The correct spelling is "conditions_levels" (which is the one that is translated in Transifex - no change to expect, I think). I will also change it in the editing form.

> in WP/hut, access_period should be used also in display mode

It seems that the attribute is actually displayed but with the standard title "access_period" whereas in the editing form the title depends on the WP type: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/edit.html#L743-L745

I have moved this point to https://github.com/c2corg/v6_ui/issues/850#issuecomment-258609333

**Comment by loicperrin** [comment] 2016-11-05 22:01
> This is already a translation (there is no string in French in the code). If you change the UI to italian for instance, this becomes "Ghiacciaio".

OK. I have not found it in Transifex, probably because the translation has been fixed 2 days ago, and so is not visible yet on demo.

> Actually, the "display" page uses the correct title (the attribute is indeed "avalanches"). The problem is in the editing form that uses "avalanches_info" whereas this string is used nowhere else and is not related to an attribute

Are you sure? I do not find "avalanches" in Transifex and it does not change when I change the interface language. I just wanted to change "avalanches" to "Avalanches observées" (as in edition mode).

I have changed some translations in Transifex (as described in my comment above)

**Comment by asaunier** [comment] 2016-11-06 11:29
> I do not find "avalanches" in Transifex

Because it was not used as an attribute name to translate (only "avalanches_info"). The actual attribute name is "avalanches" in the database => that's the name we should use for translations as well.

When PR #851 is merged, "avalanches" will be pushed to Transifex instead of "avalanches_info".

**Comment by loicperrin** [comment] 2016-11-06 21:50
A new one:
- [ ] in WP/site, the field after "Accès" should have a title in edition mode, and the title in display mode should be changed with a new Transifex label (access_period is used with another sense)

**Comment by shortoland** [comment] 2016-11-07 18:54
Am I the only one finding it's becoming a big mess ? ;-)
Could it be possible to upload translations in order to recheck everything ?

**Comment by asaunier** [comment] 2016-11-07 20:57
> Could it be possible to upload translations in order to recheck everything ?

I have updated the "dev" (unofficial) demo and made sure the translations are fully downloaded from Transifex again.

**Comment by loicperrin** [comment] 2016-11-07 21:55
- [ ] when creating/editing a document, in the last step, the "document_quality" list contains strings not coming from Transifex (I have checked they are always translated).

**Comment by asaunier** [comment] 2016-11-07 23:11
> when creating/editing a document, in the last step, the "document_quality" list contains strings not coming from Transifex (I have checked they are always translated).

See https://github.com/c2corg/v6_ui/issues/880

> in route display page, the attribute for "Materiel glacier" does not come from Transifex (no instead of non)

Will be fixed by https://github.com/c2corg/v6_ui/pull/881

**Comment by ginold** [comment] 2016-11-09 11:02
- [ ] "glacier_safety_gear" is not translated.

**Comment by asaunier** [comment] 2016-11-09 11:06
> "glacier_safety_gear" is not translated.

Where?
Its translation is available in Transifex. But perhaps the translation of your instance are not uptodate?

**Comment by asaunier** [comment] 2016-11-09 11:11
I have just updated the "dev demo" instance, including the translations. "glacier_safety_gear" seems translated as expected http://c2corgv6.demo-camptocamp.com/routes/54629/fr/breithorn-w-traversee-klein-matterhorn-refuge-guide-du-val-d-ayas

**Comment by shortoland** [comment] 2016-11-09 11:32
I have unchecked a box in my original request: "Outing creation ("ski", ): criteria "Qualité de la neige" and "Quantité de neige" do not have their own answers. Some are common with public transportation criteria, but translations are different:"

Not fully sure you didn't mention this in another ticket: should we change translations or should you add new dedicated answer strings ?

**Comment by asaunier** [comment] 2016-11-09 11:40
>  criteria "Qualité de la neige" and "Quantité de neige" do not have their own answers. 

Both uses "condition_ratings" as values
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L527-L533

> Some are common with public transportation criteria, but translations are different:"

Waypoint's ``public_transportation_ratings``:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L106-L112

There are no common values for both list of values.

**Comment by shortoland** [comment] 2016-11-09 11:45
OK, my original post was not clear:
"Qualité de la neige" and "Quantité de neige" have the same aswers, which is normal.

But there are the same as "Evaluation des conditions".

Answers are almost the same, but rather singular for the snow, and plurial for conditions.

**Comment by asaunier** [comment] 2016-11-09 12:09
Values are the same for those 3 attributes, as expected in the specs:
https://docs.google.com/spreadsheets/d/110umbpgS1CUDtzeJ62fNBvn9UBHl_wSbXx5xhFlQTng/edit#gid=792641820

**Comment by shortoland** [comment] 2016-11-09 13:27
OK.
@loicperrin: Should we change "Quantité" and "Qualités" in "Quantités" and "Qualités" in order to fit with plurial answers ?

**Comment by loicperrin** [comment] 2016-11-09 21:36
> Values are the same for those 3 attributes, as expected in the specs:

Not exactly: as said by @shortoland, "Evaluation des conditions" has plurial answers (singular for the 2 others).

> Should we change "Quantité" and "Qualités" in "Quantités" and "Qualités" in order to fit with plurial answers ?

OK for "Quantités". I prefer keep "Qualité". That's a minor problem if translations are plurial for this field. This can be modified later if necessary.

**Comment by asaunier** [comment] 2016-11-09 22:18
> That's a minor problem if translations are plurial for this field. This can be modified later if necessary.

If values must actually be different between condition ratings and snow quantity/quality fields, a new set of values must be created before the migration/golive (it impacts the database).

**Comment by shortoland** [comment] 2016-11-10 09:44
I agree. Let's keep "Quantité" et "Qualité", and create a new set of values for their corresponding answers.

**Comment by asaunier** [comment] 2016-11-10 13:54
Do we really need those quantity/quality fields? I have the feeling we are wasting time about silly attributes that are anyway confusing.

**Comment by shortoland** [comment] 2016-11-10 14:38
Ah ... this is another problem. I let Loic and others answer ...

**Comment by asaunier** [comment] 2016-11-10 15:51
@loicperrin @shortoland 
Forget my comment, we'll leave those attributes as is but won't make changes about the values either.
I suggest to use neutral translations for instance "bon", "moyen", "excellent" for the 3 attributes, not considering the gender and number of the attribute name translations.

**Comment by loicperrin** [comment] 2016-11-10 21:58
> I suggest to use neutral translations for instance "bon", "moyen", "excellent" for the 3 attributes, not considering the gender and number of the attribute name translations.

OK for this.

**Comment by loicperrin** [comment] 2016-11-13 22:06
One question: is "Snow" value used somewhere else than in "Conditions de l'accès" (outing)? If not, the french translation has to be changed to "enneigé".

**Comment by asaunier** [comment] 2016-11-14 07:53
> One question: is "Snow" value used somewhere else than in "Conditions de l'accès" (outing)? If not, the french translation has to be changed to "enneigé".

You may find the answer by yourself having a look at the lists of attributes values here: https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py

``snow`` is used for
* ``ground_types`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L84
* ``access_conditions`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L517
* ``image_categories`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L567

I can change the value for ``access_conditions`` to ``snowy`` if you prefer.

**Comment by loicperrin** [comment] 2016-11-14 23:10
> I can change the value for access_conditions to snowy if you prefer

Yes!
Maybe it should be useful to change also the value for image_categories, as the translation will not be the same as for ground_types.

**Comment by asaunier** [comment] 2016-11-15 08:51
> Maybe it should be useful to change also the value for image_categories, as the translation will not be the same as for ground_types.

Wouldn't if be "neige" in both cases? What's the french translation of the image category "snow"?

**Comment by desnoes** [comment] 2016-11-16 21:17
- [ ] the field 'Type de voie' is not displayed correctly when the value 'Grande voie'or 'couenne' is selected. Instead, either 'multi' or 'single' is displayed. It seems to be an error related to transifex.
![iti escalade](https://cloud.githubusercontent.com/assets/19892089/20365986/78afbd3c-ac49-11e6-9379-99408672b7f0.jpg)

**Comment by asaunier** [comment] 2016-11-16 21:26
> the field 'Type de voie' is not displayed correctly when the value 'Grande voie'or 'couenne' is selected. Instead, either 'multi' or 'single' is displayed.

There are 2 errors:
* the attribute value is not marked as to be translated in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/helpers/view.html#L74 => we (SA) have to fix this.
* the FR translations in Transifex for "multi" and "single" are... "multi" and "single". Which is obviously not correct. @shortoland a job for you :)

**Comment by loicperrin** [comment] 2016-11-16 23:31
> Wouldn't if be "neige" in both cases? What's the french translation of the image category "snow"?

The image category "snow" has to be translated into "Nivologie et avalanches", where as it should be "Neige" (ou "neige éternelle") for ground_types.

**Comment by asaunier** [comment] 2016-11-16 23:42
> The image category "snow" has to be translated into "Nivologie et avalanches", where as it should be "Neige" (ou "neige éternelle") for ground_types.

I have just made changes before seeing your answer. See https://github.com/c2corg/v6_common/pull/42/files
Ground type "snow" remains unchanged.

**Comment by loicperrin** [comment] 2016-11-16 23:47
> I have just made changes before seeing your answer

Perfect, thanks!

**Comment by asaunier** [comment] 2016-11-17 23:58
@loicperrin 

> in WP/Access (edition mode), access_period should be replaced by opening_periods ("Période de gardiennage" to be replaced by "Période d'ouverture")

This is a bit confusing to me. If we use "opening_periods" for "access" waypoints as well, "access_period" seems to be no longer needed:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/edit.html#L740-L742

Is it correct?
I have prepared a change that adapt the attribute name in the document page as well, depending on the waypoint type, see https://github.com/c2corg/v6_ui/pull/924/files

> in WP/site, the field after "Accès" should have a title in edition mode, and the title in display mode should be changed with a new Transifex label (access_period is used with another sense)

Are you talking about what follows?
<img width="261" alt="capture d ecran 2016-11-18 a 00 54 12" src="https://cloud.githubusercontent.com/assets/1192331/20412859/a47c7898-ad29-11e6-9919-36da4a19375e.png">

Is this field really needed? There is already a list of months that can be checked earlier in the editing mode:
<img width="413" alt="capture d ecran 2016-11-18 a 00 57 04" src="https://cloud.githubusercontent.com/assets/1192331/20412911/f66a045e-ad29-11e6-822a-4058cf76f67f.png">

It seems that this field should not be displayed for climbing sites, both in editing or display mode. OK for you?

**Comment by desnoes** [comment] 2016-11-18 16:02
Outing; Access field. The attribute 'Neige' seems to be a translation error (see example below).
![acces](https://cloud.githubusercontent.com/assets/19892089/20436512/c616a488-adb0-11e6-944f-2b1381967382.jpg)

**Comment by asaunier** [comment] 2016-11-18 16:13
@desnoes This problem has already been reported by @loicperrin and fixed (perhaps not already available in the demo)  See https://github.com/c2corg/v6_ui/issues/705#issuecomment-261108989

**Comment by desnoes** [comment] 2016-11-19 09:26
Translation missing : 'Books' => 'Livres'
![books](https://cloud.githubusercontent.com/assets/19892089/20454488/9acc89c2-ae42-11e6-86a1-1fd0bea66cd0.jpg)

**Comment by asaunier** [comment] 2016-11-19 10:12
@desnoes the translations are not up-to-date on the demo. It's OK on http://c2corgv6.demo-camptocamp.com/books

**Comment by stef74** [comment] 2016-11-21 10:16
@asaunier could we flag "ready for demo" ?

**Comment by asaunier** [comment] 2016-11-21 10:22
Maybe. There are a few unchecked point above but some are reported in a dedicated issue, for instance: https://github.com/c2corg/v6_ui/issues/942
In addition this issue is growing a little too big and is a bit hard to read/review.

**Comment by desnoes** [comment] 2016-11-23 20:14
> > I can change the value for access_conditions to snowy if you prefer
> 
> Yes, please!
> Maybe it should be useful to change also the value for image_categories, as the translation will not be the same as for ground_types.

'snowy' remains to be translated.

**Comment by asaunier** [comment] 2016-11-23 20:25
> Outing: snowy' remains to be translated. Same problem with 'height_diff' that should be translated in 'Dénivelé'.

Those 2 strings are available in Transifex but not translated yet.

**Comment by loicperrin** [comment] 2016-11-23 23:45
> Those 2 strings are available in Transifex but not translated yet.

Done.
Also  translated: nivology, great.
Some other values have to be translated.

**Comment by asaunier** [comment] 2016-11-28 14:37
> in WP/site, the field after "Accès" should have a title in edition mode, and the title in display mode should be changed with a new Transifex label (access_period is used with another sense)

See PR https://github.com/c2corg/v6_ui/pull/1032

@shortoland @loicperrin @desnoes @stef74 
I think the issue is more or less addressed when the PR is merged. Since it's now really to big, I think it will be better to tag it as "ready for demo" and finally close it. If other problems have to be reported, please create a new issue.

**Comment by stef74** [comment] 2016-12-02 09:24
@desnoes @loicperrin could you check ? if new issue please open a new issue

**Comment by desnoes** [comment] 2016-12-02 09:45
Outing: there are still 3 bugs
- 'height_diff': @asaunier did a PR for this issue (https://github.com/c2corg/v6_ui/pull/1069)
- 'True' instead of 'yes': i don't know wether it is a translation error or not

![sortie](https://cloud.githubusercontent.com/assets/19892089/20829451/669348dc-b87c-11e6-9953-c3e3795b1cce.jpg)

**Comment by asaunier** [comment] 2016-12-02 11:06
@desnoes please don't add new things to this issue, it's too big now. I have moved your report to https://github.com/c2corg/v6_ui/issues/1077

I recommend closing the issue if other points are OK.

**Closed** 2016-12-04 09:23 UTC
Labels: fixed and ready for testing

**Comment by loicperrin** [comment] 2016-12-05 23:06
I confirm that other points OK, and translations in Transifex too.
