### ISSUE TITLE
Permalink to outing list with date criteria do not work

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1410] opened 2017-01-21 20:53 UTC
Ex : https://www.camptocamp.org/outings#date=2017-01-16,2017-01-21

Then, when we search last outings with the filter, then we want to update the results by reloading the page, it doesn't work, and we must return to default filter and set the criteria one more time...

**Comment by asaunier** [comment] 2017-01-22 21:44
Duplicate of https://github.com/c2corg/v6_ui/issues/1295

**Closed by asaunier** 2017-01-22 21:44 UTC
Labels: advanced Search, bug
