### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#753] opened 2016-10-19 11:55 UTC
> the info about the licence of the document is shown nowhere.
#449

**Comment by asaunier** [comment] 2016-10-19 11:58
Are you sure this is really a "beta" issue?
It's rather a "cosmetic" work depending on the document type or some other attribute.

**Comment by stef74** [comment] 2016-10-19 12:02
it's a go live issue ...

2016-10-19 13:58 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment] 2016-10-19 12:10
So the milestone should rather be "go live"?

**Comment by stef74** [comment] 2016-10-19 13:47
For me go live = beta + critical bug ... but I changed for go live

**Comment by asaunier** [comment] 2016-11-03 11:47
Complements to this issue:
* depending on the document type (+ some additional attribute for images or articles), the licence of the document should be made obvious in the detail view pages.
* see the CC logo (depends on the licence of the document) at the bottom of http://www.camptocamp.org/routes/211687/fr/mont-de-grange-traversee-bel-air-coicon
* something similar is needed for v6 (logo + text and links toward the licence page). Note sure where to place this part since now comments are in the way. @ginold what do you think?

Reminder:
* WP, routes, books, regions, collaborative articles, collaborative images => licence is CC BY SA https://creativecommons.org/licenses/by-sa/3.0/deed.fr
* outings, profiles, personal articles, personal images, accident reports => licence is CC NY NC ND https://creativecommons.org/licenses/by-nc-nd/3.0/deed.fr

**Comment by ginold** [comment] 2016-11-03 12:51
>   Note sure where to place this part 

this can be put just before the comments or just after the description text. Or add one row to the 'information block' with 'licence : CC BY SA' and tooltip with the explanation text.

**Comment by asaunier** [comment] 2016-11-03 13:14
> add one row to the 'information block' with 'licence : CC BY SA' and tooltip with the explanation text.

:+1: 
Please use the CC logo, not "licence : CC BY SA"

**Comment by ginold** [comment] 2016-11-03 13:32
BY - attribution
SA - share
ND - not commercial
NC - no changes
NY - ??? i only find new york :P

**Comment by asaunier** [comment] 2016-11-03 13:51
NY => typo, I meant BY

**Comment by stef74** [comment] 2016-11-04 15:59
@loicperrin @desnoes @shortoland please test

**Comment by asaunier** [comment] 2016-11-04 16:01
> @loicperrin @desnoes @shortoland please test

problably not on the official demo yet (OK on the old one)

**Comment by loicperrin** [comment] 2016-11-07 17:21
There is a little problem with tooltip on licence info in some documents: route, WP/access.
When I put the mouse over the icon "ShareAlike", the tooltip flashes. 
It happens only when this icon is at the end of the line. If I modify the screen size to put it at the begining of the following line, the problem do not happen.

**Comment by shortoland** [comment] 2016-11-07 17:24
@asaunier OK on old version, but I couldn't check books nor accidents reports.

Can you check that logo for SERAC home page is the good one ?

![image1](https://cloud.githubusercontent.com/assets/20488365/20067939/30b40ba2-a517-11e6-841b-42967f75ea25.png)

Don't have Loic's problem: no flashing tooltip (on firefox)

**Comment by asaunier** [comment] 2016-11-07 19:58
> I couldn't check books nor accidents reports.

They are not available yet.

> Can you check that logo for SERAC home page is the good one ?

What do you mean? What logo?
This page is a simple article, it will be used until reports are available (not before v6.1).

By the way what is the connection with licence info? :P 

> There is a little problem with tooltip on licence info in some documents: route, WP/access.
When I put the mouse over the icon "ShareAlike", the tooltip flashes. 
It happens only when this icon is at the end of the line. If I modify the screen size to put it at the begining of the following line, the problem do not happen.

@loicperrin I cannot reproduce this problem whether with FF or Chrome. Could you provide a screenshot of the screen size that causes the problem?

**Comment by shortoland** [comment] 2016-11-07 20:09
> By the way what is the connection with licence info? 

I meant: there is a licence logo on the SERAC homepage: is it normal ? is it the right one ?

**Comment by loicperrin** [comment] 2016-11-07 20:11
I reproduce this problem with FF (not tested with Chrome). See: 
![issue753](https://cloud.githubusercontent.com/assets/19718055/20073986/b79fd580-a52e-11e6-8017-c76c7821d0b9.jpg)

**Comment by asaunier** [comment] 2016-11-07 20:28
> there is a licence logo on the SERAC homepage: is it normal ? is it the right one ?

It's correct. The licence logo is the one for the article (which is collaborative), not SERAC itself.
SERAC reports will have their own licence logos (the same then for outings).

> I reproduce this problem with FF (not tested with Chrome).

OK thanks!
@ginold do you have an idea?

Honestly it's a really minor issue, it happens only for some screen sizes and resolutions, and only when hovering the icon.

**Comment by ginold** [comment] 2016-11-08 08:28
I think I experienced this issue but I don't know yet why it's happening. If not critical, I will look at it later.

**Comment by loicperrin** [comment] 2016-11-08 21:55
Yes it is not critical, and except this minor problem, license information seems to be OK.

**Comment by asaunier** [comment] 2016-11-12 19:37
OK, then I close the issue, please reopen if this problem really needs to be fixed.

**Closed by asaunier** 2016-11-12 19:37 UTC
Labels: bug, low prio
