### ISSUE TITLE
Feed update when adding images to an outing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#816] opened 2016-10-28 13:05 UTC
(maybe rather an API question)

I have uploaded images to 2 outings (made no other change in the outings) and the feed reports that I have updated those outings. Shouldn't it report that I have added images to them, instead?

On the other hand I have also uploaded images to a route previously and the feed actually reports that I have added images to it.

![sans titre](https://cloud.githubusercontent.com/assets/1192331/19807349/f64c6206-9d1f-11e6-9428-9e1477c0452c.png)

**Comment by ginold** [comment] 2016-10-31 16:59
how is that a UI question? it seems to be an API issue - not returning feed as it should ? Or it depends which point of view you take: might be UI if you're asking if the feed displayed is how we want it to be. :walking_woman:

**Comment by asaunier** [comment] 2016-11-02 08:48
Yes, that's most likely an API issue but I wanted to make it appear in the UI issues as well because testers might anyway report it here.

I have just created an API issue for this: https://github.com/c2corg/v6_api/issues/464

**Comment by tsauerwein** [comment] 2016-11-04 15:43
In fact, this not an API issue: The API returns the images for the feed entries. I think the problem is that the UI is only displaying the images if the feed type is `added_photos`. The feed entries for all feed types may have images.

When a user is changing a document or adding images to a document that they created them-self, the feed type is `updated`. If a user is adding images that they did not create them-self, the feed-type is `added_photos`.

**Comment by fjacon** [comment] 2016-11-09 07:48
If a user changes a document he created himself, do we want to have 2 reports : 1 `added_photos` and 1  `updated` ?
@tsauerwein  is this technically possible anyway ?

**Comment by tsauerwein** [comment] 2016-11-20 15:21
@fjacon I think your questions where resolved in https://github.com/c2corg/v6_ui/issues/878#issuecomment-259354796.

What is left to do in this issue is to show the images for all feed activity types (all types may contain images).

**Comment by tsauerwein** [comment] 2016-11-23 14:20
@stef74 You could keep this for Go Live. This is a simple change in a template.

**Comment by mgerbaux** [comment] 2016-11-26 10:38
I add images on my outings (but do nothing else for edition), but it never appear in the feed ; it is just mentioned as outing edition
[](http://i.imgur.com/kTM44g6.png)

**Comment by loicperrin** [comment] 2016-11-30 00:00
I have seen the same problem (sorry if already fixed but not visible on demo):
- If I add an image on an outing I have created: the feed tells "Loïc Perrin a mis à jour une sortie"
- If I add an image on an outing I have not created (*): the feed tells "Loïc Perrin a ajouté des images pour cette sortie"

(*) Maybe this is also an issue, as I should not be authorized to add image on on outing I have not created (but maybe it is normal with my "modo rights").

**Comment by asaunier** [comment] 2016-11-30 07:55
> Maybe this is also an issue, as I should not be authorized to add image on on outing I have not created (but maybe it is normal with my "modo rights").

Yes => moderator rights allow to upload images on any document. Please rather test with a normal user.

**Comment by tsauerwein** [comment] 2016-11-30 07:59
@loicperrin This is the behavior we agreed upon. See https://github.com/c2corg/v6_ui/issues/878#issuecomment-259354796

**Comment by loicperrin** [comment] 2016-12-01 22:22
> This is the behavior we agreed upon.

Yes you are right. What is disturbing was the fact that the image was not included it the feed when added to my own outing. Now it is OK

**Closed by loicperrin** 2016-12-01 22:22 UTC
Labels: blocking, fixed and ready for testing, Home Page / activity feed, question
