### ISSUE TITLE
Blank lines are not supported in tags "important" and "warning"

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1619] opened 2017-05-04 12:19 UTC
The balise does not work when a blank line is inserted within the text.

The follwing example gives the result shown in the screenshot below
[important]
AVERTISSEMENTS

- Lisez attentivement la notice technique avant de regarder les techniques suivantes.
- Vous devez avoir compris les informations de la notice technique pour pouvoir comprendre ce complément d’informations.
- Maîtriser ces techniques nécessite une formation et un entraînement spécifique.
- Validez avec un professionnel votre capacité à refaire la manipulation, seul, en toute sécurité, avant de la reproduire en autonomie.
[/important]

![bug balise](https://cloud.githubusercontent.com/assets/19892089/25703146/a216c6f6-30d4-11e7-8443-e397dca9ac31.png)

**Comment by asaunier** [comment] 2017-05-18 13:13
According to my tests:
* OK if the contenu is on several lines but with no embedded blank line
* KO if one or more blank line is embedded
* same problem with the ``[warning]`` tag (probably same reason and solution)

Perhaps the problem is that the regular expression forbids (??) blank lines:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/important.py#L12

Or (most likely) because adding blank lines means that a new block is created, the element being no longer "inline" and then the "inline pattern" can no longer be used (might be quite annoying to change this behaviour):
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/important.py#L23

**Comment by cbeauchesne** [comment] 2017-12-02 12:44
Hello,

This issue will be resolved by #1838 : recoding another syntax for alerts. I've added unit tests for all case (I've seen 😉  ).

Once #1838 will be in prod, I will migrate with the bot olds tags. And then, we will remove ImportantExtension and WarningExtension.

**Closed** 2018-01-10 18:26 UTC
Labels: parser, wontfix
