### ISSUE TITLE
Toggling between Maps and list of cards doesn't resize the searching fields on Vivaldi browser 

### ISSUE THREAD

**Issue by AlexisDemongeot** [c2corg/v6_ui#1374] opened 2017-01-17 10:21 UTC
![image](https://cloud.githubusercontent.com/assets/24522280/22016570/0bf7eff0-dca7-11e6-9b8a-42aab855d512.png)

When toggling between map and list of cards, the advance research field is not reduced.
Some searching fields are not any more useable.

Vivaldi browser 1.6.689.40 (Stable channel) (32 bits)
https://fr.wikipedia.org/wiki/Vivaldi_(navigateur_web)

**Comment by brunobesson** [comment] 2017-01-23 13:11
@AlexisDemongeot could you be more explicit? I don't understand exactly what is the problem you describe. I installed Vivaldi Browser on my computer (v1.6, Linux), and I don't see anything strange happening.

**Comment by AlexisDemongeot** [comment] 2017-01-23 13:45
@brunobesson just look in the searching field in the center : you can't reach what it's on the right : duration and so on ...

**Comment by brunobesson** [comment] 2017-01-23 13:52
OK, I think I get it. Still I cannot reproduce your behaviour: what I observe is:

* have bothe the list and map shown
* expand advanced filters
* hide map
* filters are not resized

How do you manage to show the map previously hidden with advanced filters expanded?

**Comment by AlexisDemongeot** [comment] 2017-01-24 09:26
What I observe is:

- open the topoguide, searching itinerary
- have both the list and map shown
- hiding the list - show the map on the entire page, ok
- show the list - show both the map and list = ok
- hiding the map - show only the list = ok
- show the map - not ok : the searching "normal" fields are not visible on the right : filters are not resized
- expand advanced filters does not solved the problem = filters are not resized

> How do you manage to show the map previously hidden with advanced filters expanded?

I do not understand the question, sorry.

**Comment by brunobesson** [comment] 2017-01-24 11:32
>show the map - not ok : the searching "normal" fields are not visible on the right : filters are not resized

That's what I cannot reproduce on the vivaldi browser I installed, hence the question you don't understand: I am unable to reach this state.

**Comment by AlexisDemongeot** [comment] 2017-02-23 19:31
@brunobesson : do you use Vivaldi on Linux or Windows ? It appears that the issue is only on Windows, I don't have this issue on Linux (same version). So what ? Do we close the issue considering it's a Microsoft artefact ?

**Comment by brunobesson** [comment] 2017-02-23 23:34
I tested on Linux. No idea how to deal with the issue... I would probably
close, usage is really low. Unless someone is willing to look after it? I
don't have the tools (no windows)

Le 23 févr. 2017 8:31 PM, "AlexisDemongeot" <notifications@github.com> a
écrit :

@brunobesson <https://github.com/brunobesson> : do you use Vivaldi on Linux
or Windows ? It appears that the issue is only on Windows, I don't have
this issue on Linux (same version). So what ? Do we close the issue
considering it's a Microsoft artefact ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/c2corg/v6_ui/issues/1374#issuecomment-282095480>, or mute
the thread

**Comment by asaunier** [comment] 2017-05-07 12:04
Honestly I think we cannot afford supporting Vivaldi (I mean do special investigations and work for it), only recent versions of Firefox, Chrome, Edge and Safari.
Then I prefer closing the issue. Thanks for reporting anyway!

**Closed by asaunier** 2017-05-07 12:04 UTC
Labels: low prio

**Comment by AlexisDemongeot** [comment] 2017-05-07 12:38
Ok. No problem for me. Thanks for the works.
