### ISSUE TITLE
Error on some outing's versions page because of missing geometry

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#1491] opened 2017-02-10 09:28 UTC
~~Related to https://github.com/c2corg/v6_ui/pull/1479 ?~~

~~Maybe we should remove/adjust this also https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L149-L151 ?~~

On this page http://localhost:6558/outings/808860/fr/1273493 I get error:

```
pyramid_mako.MakoRenderingException: 
Traceback (most recent call last):
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/base.html", line 150, in render_body
    vcRecaptchaServiceProvider.setSiteKey('${settings["recaptcha_site_key"]}');
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/outing/view.html", line 38, in render_moduleConstantsValues
    <%
TypeError: 'NoneType' object is not subscriptable
```

**Comment by asaunier** [comment] 2017-02-10 10:00
I don't think it has a connection with #1479 since the latter PR made no change in ``settings["recaptcha_site_key"]``.

Are you sure your ``recaptcha_site_key`` is set in your ``common.ini``?

**Comment by tsauerwein** [comment] 2017-02-10 10:06
We just looked at it together, it's unrelated to recaptcha. The problem is here:
https://github.com/c2corg/v6_ui/blob/ac2ceada040b0813739bcd008effdbd38439fd8b/c2corg_ui/templates/outing/view.html#L39

Old versions of outings might not have a geometry. I guess this is also the case for other document types?

**Comment by asaunier** [comment] 2017-02-10 10:12
> I guess this is also the case for other document types?

 I don't know but it's quite likely.

**Comment by desnoes** [comment] 2017-02-21 19:50
@dkocich @asaunier @tsauerwein : do you have an outing that was in error ? I am unable to test.

**Comment by dkocich** [comment] 2017-02-21 19:54
It is mentioned in the first comment https://www.camptocamp.org/outings/808860/fr/1273493

**Comment by desnoes** [comment] 2017-02-21 20:22
Sorry, i did catch the issue. I have access to all versions of https://www.camptocamp.org/outings/808860/fr/1273493
What is the error ?

**Comment by dkocich** [comment] 2017-02-21 20:25
That page URL returned just "internal server error". It is fixed now. :)

**Comment by desnoes** [comment] 2017-02-21 20:27
ok, i was expecting an error on the prod site which would have been fixed on the demo, but it is already fixed on the prod site. You confirm ?

**Closed** 2017-03-03 15:02 UTC
Labels: fixed and ready for testing
