### ISSUE TITLE
Display issue when editing a route or entering a new route

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#683] opened 2016-10-04 20:36 UTC
When editing a route, there is a display issue in chapter "Configuration":

![image1](https://cloud.githubusercontent.com/assets/20488365/19091424/d555bf34-8a82-11e6-9c32-2b588ab7aaff.png)

I am wondering if Loic already reported this, but I cannot find anything.

**Comment by asaunier** [comment] 2016-10-04 21:53
> I am wondering if Loic already reported this, but I cannot find anything.

Yes, it's a duplicate of https://github.com/c2corg/v6_ui/issues/617

**Closed by asaunier** 2016-10-04 21:53 UTC
