### ISSUE TITLE
Parsing of L# tags

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#713] opened 2016-10-08 21:35 UTC
(Simple) example of L# code:

```
L# | 6a | 10 m  | Courte longueur, des pas fins
L# | 6a+ | 30 m  | Grande longueur, deux pas fins en 6a+ (début et fin de voie), sinon 5c/6a
L# | 5a | 30 m | En ascendance vers la droite puis droit au dessus. On passe un premier relais optionel (pour le rappel) et on atteint peu après un second relais au pied du mur suivant.
L# | 6a | 25 m | En ascendance à droite, magnifiques écailles.
L# | 6b+ | 25 m | Longueur soutenue en 6b/c, plusieurs points d'aide sont en place (anneaux de cordes).
```

Complete usage doc: http://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs

This syntax is actually composed of 2 things (to be parsed separately?):
- a kind of table syntax (based upon `|` separators) => beware of conflicts with the wikilink syntax, see https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/wikilinks.py
- a "pitch" identifier where `#` is replaced by an integer, eg. L1, L2, L3, etc.

Source code of v5 parser: around https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1516

There are many options for the pitch numbering.
The goal of this issue is to provide a base support that should be enough for most of the cases:
- table
- simple incrementation of pitches

Using the standard python-markdown extension for tables has been tested but does not seem to give satisfaction. See the report at https://github.com/c2corg/v6_ui/pull/695#issue-181277786

Part of issue https://github.com/c2corg/v6_ui/issues/131

**Comment by asaunier** [comment] 2016-10-11 19:58
> This syntax is actually composed of 2 things (to be parsed separately?):

I am finally not that sure the numbering and the table syntax should be processed separately.

Pros:
* we could use the table syntax for more standard usages. Is it needed?

Cons:
* using ``L#`` as the opening marker of the table row (combined to the following ``|`` delimiters) would help identifying a row and prevent conflicts
* we probably don't need to replace ``L#`` out of a table row

If keeping the combination of ``L#`` and ``|`` we can probably use a variant of the standard table extension, already tested. To avoid conflicts with wikilinks, we have to make sure the wikilinks are evaluated first by the parser. See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/wikilinks.py#L26

By the way I have noticed another rendering of ``L#`` tags => in climbing site pages. See for instance http://www.camptocamp.org/sites/102880/fr/le-chaney
=> lines are alternately colored and there is no "L" in the pitch numbering (btw not bolded).
@fbunoz could you explain what causes this difference?

**Comment by stef74** [comment] 2016-10-12 08:46
Table syntax is very interreting in many case !

2016-10-11 21:58 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by fbunoz** [comment] 2016-10-13 20:49
> could you explain what causes this difference?

The doc type is used to generate a different html. The global variable $doc_module is set here : https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1448
and it is used in sub functions : 
- https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1570-L1578
- https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1885-L1892
- https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1974-L1981

**Comment by asaunier** [comment] 2016-10-14 07:28
In my opinion it's crazy that a tag is parsed differently depending on the document type :(

**Comment by asaunier** [comment] 2016-12-05 11:18
@fbunoz @stef74 Is there a chance that this parser is ready for demo? If not, it's no use keeping it on milestone "golive", perhaps we could postponed to 6.1?

**Comment by stef74** [comment] 2016-12-05 20:20
No infos ...

**Comment by fbunoz** [comment] 2016-12-05 20:27
No chance for thursday.
These last weeks, I spent the most dev time to check the migrations and correct the fails in V5 db.

**Comment by asaunier** [comment] 2016-12-11 18:22
@fbunoz Any update about this L# tag?
Could you create a branch of what you have done?

**Comment by olaurendeau** [comment] 2017-04-20 08:08
Hello @asaunier @fbunoz
I would be interested in giving a hand on this issue. If I understand well @fbunoz already built something ? Is it available somewhere ?
Thanks :)

**Comment by asaunier** [comment] 2017-04-21 16:53
Hi @olaurendeau 
thanks for offering your help :) It's definitely welcome but I have no info about the status of this task. @fbunoz could you precise? thanks!

**Comment by cbeauchesne** [comment] 2017-04-21 17:25
Hi,

FYI, I've made a big part of the job (even details are always the hardest part...) here : https://github.com/cbeauchesne/campui/blob/master/app/static/js/markdown.js

But it's on client side.

There are some pro/con to consider on doing this on client part:

* *Pro*
  * Server CPU economy (even it's not so expensive, if it's done once)
  * Bandwidth economy (even it may not be so big). 
  * **Code ready for the *preview feature* on edition** this one is definitively a killer argument.
* *Con* to be frank, I do not see relevant cons. But I do not have a good vision on project constraint. Let's say :
  * slowness of render on low CPU phone?
  * javascript regex are easy to unit test as Python?

If you decide to do it on client side, I will be glad to contribute.

**Comment by olaurendeau** [comment] 2017-04-21 17:29
👍 So @cbeauchesne you are handling the subject if I understand well ?

**Comment by cbeauchesne** [comment] 2017-04-21 20:39
Not exactly, it's for an alternative user interface using the API, but that redefines front app. That's why I've done this job, markdown must be interpreted on client side for my project.

By the way, for every parts that will be in common, I'd be totally open to joins our efforts.

**Comment by olaurendeau** [comment] 2017-04-22 17:01
Oki, then I would be glad to give a hand for the classic UI. Giving a deeper look I assume it would make sense to build a HTML table in the backend, in the same way wikilinks are built https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/wikilinks.py

I'm just not sure about suffix parsing according to @cbeauchesne code https://github.com/cbeauchesne/campui/blob/master/app/static/js/markdown.js#L278 there is a lot of possibilities, @asaunier could you point me out where parsing was done in v5 ?

I foresee that @cbeauchesne regexes will be very useful !

**Comment by asaunier** [comment] 2017-04-23 17:07
The parsing of L# tags must be performed on the UI server side for at least 2 reasons:
* other tags are converted server side, it's a no sense to have some tags converted server side, others client side
* server side conversion of the tags is required to have the documents correctly interpreted (and indexed) by search engines.

> Giving a deeper look I assume it would make sense to build a HTML table in the backend, in the same way wikilinks are built https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/wikilinks.py

@olaurendeau exactly!
We use python-markdown and custom extensions to convert the tags. See explanations and examples of existing extensions at https://github.com/c2corg/v6_ui/tree/master/c2corg_ui/format

> could you point me out where parsing was done in v5

I don't know much about this parser in v5. @fbunoz has developed it and is better placed to give tips. It seems this is done around this function:
https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1854

Please note the L# parsing is really really complex. See for instance the help article which is very long: https://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs
I am not sure we should reimplement all those use-cases.
Perhaps a simple incrementation of pitch numbers is enough when using L#. For advanced usage, such as L1-L4, L3' etc. perhaps we could simply allow explicit numbering (we need something simple enough to be understood by contributors).

**Comment by cbeauchesne** [comment] 2017-04-23 19:58
Hi Alex,

To be frank, I do not understand your points : 
* obviously, it wouldn't be a good idea to part of the job on the server, and part on the client, I suggest to do all the job on client side. JS plugins for markdown rendering are very reliables.
* For search engines, if I'm not wrong, crawlers can now handle pretty well angular pages. By the way, extracting content from raw markdown would be easy...

But, I'd guess that you have good reasons to prefer server rendering.

FYI, my code handles all cases exposed in https://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs , except what I've not seen 😉

**Comment by fbunoz** [comment] 2017-04-23 20:28
> FYI, my code handles all cases exposed in https://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs , except what I've not seen

There are some mistakes on this page for instance : http://campui.eu-west-2.elasticbeanstalk.com/waypoint/198933

- The suffix must be initialized if we force the number (the suffix is also forced when we force the number, then it is often forced to null).
- A blank line can be added between two L# line in the edit code without generate a new table. It is useful to clarify the edit code.
- The L# tag can be used in a L# cell (see the [article](https://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs#mention-du-numero-de-la-longueur-dans-la-description))

**Comment by cbeauchesne** [comment] 2017-04-23 21:25
Thank you very much, back to workbench

Btw, @fbunoz, I'm interested by your point of view on client/server rendering.

**Comment by cbeauchesne** [comment] 2017-04-23 22:22
Point 2, 

```
 L# : aaa
 
 L# : b
```

That should create this ?
<table><tbody><tr><td>L1</td><td>aaa</td></tr><tr><td>L2</td><td>b</td></tr></tbody></table>

If yes, it still ok I think, do you have an example where it fails?

**Comment by fbunoz** [comment] 2017-04-23 22:38
> do you have an example where it fails?

It fails in the table after the subtitle "Chacal Bondissant" in the doc whose I have given the url : the last col shouldn't be created. It is caused by some ':' in the text (ex : "point assez mal placé : pendule en cas de chute").

**Comment by cbeauchesne** [comment] 2017-04-23 22:54
I've just fixed this one https://github.com/cbeauchesne/campui/commit/3b17c2716594264972933fa83b88181dcd5d6ccd

It's this point I do'nt understand :

> The suffix must be initialized if we force the number (the suffix is also forced when we force the number, then it is often forced to null).

**Comment by fbunoz** [comment] 2017-04-23 22:59
On the sector Ice Bill, the number is L1" , L2" , whereas it should be L1 , L2
Because the tag is L#1 : then the current suffix " is reset by a tag with a forced number.

**Comment by cbeauchesne** [comment] 2017-04-23 23:03
Ok, thank you very much

**Comment by asaunier** [comment] 2017-04-24 08:09
@cbeauchesne This issue is not about your implementation of the L# in your frontend. It's about the v6 UI. Then please don't pollute it with not related considerations.
It's not even the place to discuss if the tags should be converted client-side or server-side: in v6 UI we have chosen to do it server-side. It's not debatable.

If you're eager to help with the creation of a python-markdown extension to support the L#, you're welcome.

**Comment by cbeauchesne** [comment] 2017-04-24 08:41
> we have chosen to do it server-side. It's not debatable.

At least it's crystal clear...
But you will understand that, with this kind of answer, you will surely discourage any contributors to help... 

Sorry for the pollution.

**Comment by desnoes** [comment] 2017-05-06 09:17
@olaurendeau: are you still volunteer to implement the parser for L# tag ?

**Comment by olaurendeau** [comment] 2017-05-07 12:22
Hello !
Yes indeed, I've started working on a first use case : implementing a "table" parser based on "|" chars.
But while i'm confortable with php & js regex flavor, python one is driving me crazy :D
I have good hope to propose a first Pull Request soon :)

**Comment by stef74** [comment] 2017-05-09 08:08
Don't hesitate to ask question ... and propose a 1st simple version.

**Comment by olaurendeau** [comment] 2017-05-10 08:06
Thanks :)
On one hand, Python Markdown propose a table extension https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/tables.py, whose syntax is not the same as camptocamp one but I plan to use it as an inspiration.
On the other hand I finally managed to built a regular expression matching the "pipe" case https://regex101.com/r/g2Zjqn/1/

**Comment by stef74** [comment] 2017-05-10 08:09
For me it's better to use markdown extension because offer table for other
usage

2017-05-10 10:06 GMT+02:00 Olivier Laurendeau <notifications@github.com>:

**Comment by asaunier** [comment] 2017-05-10 08:12
> matching the "pipe" case 

Are there other cases?
Perhaps you mean  the other syntax ``L# : texte 1 :: texte 2 :: texte 3 :: … :: texte n``?
I don't understand why we need this alternate syntax. Perhaps we could simply ignore it?

> For me it's better to use markdown extension because offer table for other
usage

I had already tried enabling the standard markdown extension for tables and it didn't work for the L# syntax.

**Comment by olaurendeau** [comment] 2017-05-10 08:24
Yes I mean the `L# : texte 1 :: texte 2 :: texte 3 :: … :: texte n` syntax, I've plan to ignore it, at least in a first time, but indeed would be great to get rid of it 👍 

The way I see it, I would like to split the "L# tag" feature in two extensions.

- A table extension handling the `col1 | col2 | col3` syntax
- A LTag extension handling the `L#` syntax

**Comment by cbeauchesne** [comment] 2017-05-10 08:30
I confirm that this extension won't handle 1% of the case. And, spoiler alert, table stuff is not the hardest point. Handling numbering is the real pain. Handling new lines inside cells is also quite difficult.

@olaurendeau having two extension is not a good solution, because it's the L# tag that declare the table. You can have this text : 

```  col1 | col2 | col3 ``` 

and it shouldn't be interpreted as a table...

**Comment by cbeauchesne** [comment] 2017-05-10 09:20
nota, after reflexion, it could be done in two extensions, but you should consider this pattern to determine if it's a table : 

/(?:(?:\n\n?)[LR]#[^]*?(?=\n[LR]#|\n\n))+/gm

**Comment by fbunoz** [comment] 2017-05-10 12:40
The better way is to redo the process used in the V5 : https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php#L1268-L1994

This code is based on markdown sub-title parser.
We could do the same think using markdown parser principles.
But the regexp used in the V5 should be used without any change, to have the same parsing than in the V5.

In the V6, there are many conflicts with new markdown tags : _ , * , ...
We need change the markdown parser to limit the side effects : 

- Do not detect _ text _ if there is a newline in the text, to avoid conflict with L#_
- Do not detect ** text ** if there is no word caracters at beginning / end of the text, to avoid conflict with | ** | , which is a L# cell containing the climb quality cotation (* to *****)

**Comment by asaunier** [comment] 2017-05-10 15:41
Wow! 700 lines of code to port...

Do we really need all of this? 99% of the feaures of L# were probably not used, it is already sooo complicated to understand the help article. Most use cases are simply incremental pitch numbering: L1, L2, L3.

I strongly recommend to simplify the supported features, especially for a first version.
For complex numbering couldn't we offer the possibility to number pitches by hand instead?

> In the V6, there are many conflicts with new markdown tags : _ , * , ...
We need change the markdown parser to limit the side effects :

I would recommend the other way: leave the standard markdown tags as is (we must stick to standard tags as much as possible), and change the L# syntax if conflicts are found. I don't understand the problem with L#_ (or ****) since the MD parser requires to have _ on both side of the words with no blank space right next to it.

**Comment by cbeauchesne** [comment] 2017-05-10 15:53
Actually, it may be in conflict, if you parse L# after markdown. If your extension is executed before markdown parser, everything can be handled.

**Comment by cbeauchesne** [comment] 2017-05-10 15:58
@asaunier I agree that a major part of the complexity handles only 1% of use cases.

A pragmatic way would be to identify the part we want to keep, and run a script with legacy PHP on whole DB to flag the 1% and correct them by hand.

**Comment by cbeauchesne** [comment] 2017-05-10 16:03
My suggestions on this : 

* forbid separator repetitions
* allow only one separator
* forbid new line in cells (but allow <br> tag)
* forbid single new line (ie, a empty line means end of table.

**Comment by cbeauchesne** [comment] 2017-05-10 16:21
Another question @fbunoz and @asaunier : Is there some where a unit test base for this? If no, could we establish one? I've started on my side with [this](https://github.com/cbeauchesne/campui/blob/master/app/static/campui/js/md_unittests.js), could we consider to keep a common base? 

@olaurendeau I've strongly reduced the size of [my code for numbering stuff](https://github.com/cbeauchesne/campui/blob/master/app/static/campui/js/markdown.js#L300-L361), if it could help...

**Comment by tsauerwein** [comment] 2017-05-10 16:43
> Is there some where a unit test base for this?

Some unit tests for the Markdown parser are here: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/tests/format/test_format.py

**Comment by cbeauchesne** [comment] 2017-05-10 17:14
@tsauerwein ok. What do you think about a file in JSON or XML that contains a list of objects with

* test_id
* markdown
* expected

Your code would be (json version):
```python 
def test_full_conversion(self):
    input_txt = json.load(os.path.join(base_path, 'tests.json'))

    for test in tests:
        html = self.markdown_parser.convert(test["markdown"])
        html = self.bbcode_parser.format(html)
        self.assertEqual(html, test["expected"], test["id"])
```

**Comment by fbunoz** [comment] 2017-05-10 18:41
> forbid new line in cells (but replace them by <br> tag)
forbid single new line (ie, a empty line means end of table.

No !
We want to be able to have a new line in a cell. Some pitch descriptions take many words and several sentences. To describe a little variant (not all the pitch, just the end or the beginning), it is better to have a new line, instead having a kilometer description as on old paper topos !

Allow a blank line between L# is useful to clarify the edit code in case of long pitch description.

The L# syntax is the result of thousands of uses by many contributors : you can't decide to change the syntax only because you have not be able to code the parser in five minutes !

**Comment by asaunier** [comment] 2017-05-10 19:11
> My suggestions on this :

@cbeauchesne I don't have a strong opinion, see @fbunoz 's objections, some of them probably being relevant even though I think this tag in v5 was way too complicated and should be simplified, for several reasons:
* most usages don't require all those features, simpler solutions could do the job for complex cases
* editing documents should remain reasonably easy, adding too many tag options make this really cumbersome and the documentation is really hard to read and understand
* porting all those features to v6 would require a lot of work to develop, debug and maintain
* adding too many parsers has a cost on performances

Concerning the unit tests:

> What do you think about a file in JSON or XML that contains a list of objects with

That's indeed an option. But I would rather add some test functions instead of changing function ``test_full_conversion`` because we need a global test with a realistic document where we could make sure parsers do not conflict with each other. See:
* the input https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/tests/format/input.txt
* the output https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/tests/format/output.txt

**Comment by cbeauchesne** [comment] 2017-05-10 19:12
@fbunoz, I do not decide, I only suggest.

It's really a pleasure to contribute here...

**Comment by cbeauchesne** [comment] 2017-05-10 19:14
@asaunier yes, I've seen that, and a flat file will be surely easier to maintain than a long string with plenty of \n. Both approach should be possible.

**Comment by fbunoz** [comment] 2017-05-10 19:42
>  I do not decide, I only suggest.

You suggest a major change on a github topic !
The devs will be always agree to simplify the code. But it complexify the using by contributords or visitors. The complexity of the routes which we want to describe is known and is irreductible. Then, it is either the server which manage the main part of the complexity, either the user. There is always a conflict between the devs who want simply the code, and the users who want simplify the using.

The L# syntax come from these topics : 
https://forum.camptocamp.org/t/l-balise-de-description-des-longueurs/90956 (assoce)
https://forum.camptocamp.org/t/l-balise-de-description-des-longueurs/115522 (public)

We didn't define the syntax to annoy the devs, but after many user requests !

**Comment by stef74** [comment] 2017-05-10 19:56
I'm sorry but complex syntax don't simplify the job of contributeur ... some syntax is understand by less than 10 people. 
In many case manual ordering is more simple and understandable by many people. 

@olaurendeau manage simple syntax at 1st, after "we" (with more than 4 people here) decide if you continue to implement all syntax et evaluate number of use.

**Comment by desnoes** [comment] 2017-05-10 20:02
> @olaurendeau manage simple syntax at 1st, after "we" (with more than 4 people here) decide if you continue to implement all syntax et evaluate number of use.

I fully agree with this procedure. We shall avoid too complicated tag.

**Comment by cbeauchesne** [comment] 2017-05-10 20:03
Actually, the point is that you do not have a version the is readable. So we are not arguing about making life easier for dev nor editor, but readers.

After that, my suggestions are not more than suggestions, even made on github topic. Feel free to consider them, or not. But if you want some help from myself, please avoid any useless innuendos...

**Comment by cbeauchesne** [comment] 2017-05-10 20:19
@asaunier i've created #1640 for the unit test point.

**Comment by fbunoz** [comment] 2017-05-10 21:26
> In many case manual ordering is more simple and understandable by many people.

The L# syntax allow manual ordering : 

L#1
L#2
L#2bis
L#3

But quickly you will be tired by incrementing manually the index, and for a new route you'll prefer copy N time a template like this before filling it with the data : 
L# |  | m | g | 
L# |  | m | g | 
L# |  | m | g | 

Then the syntax without explicit index is also useful.

There were several version of L# syntax, and each version was compliant with the preceding version.

**Comment by asaunier** [comment] 2017-05-11 08:55
> The L# syntax allow manual ordering :
L#1
L#2
L#2bis
L#3

That could indeed be the kind of syntax used when the standard L# syntax is not enough.

> But quickly you will be tired by incrementing manually the index

Come on! You don't have to describe El Capitan every day and doing a bit of manual work like renumbering would take less than a minute for sure :P 

> for a new route you'll prefer copy N time a template like this before filling it with the data :

OK but it is still possible to do so if L# are supported with simple autoincrementing.

Then the specs for this issue are:
* step 1: support the standard L# tags with autoincrementing only => could be a first PR that would support most cases
* step 2: offer a simple fallback when autoincrementing is not possible => use explicit numbering like L#1 for instance
* steps 3, 4, 5,...: add advanced syntax if it is really relevant (in my opinion it's not)

**Comment by olaurendeau** [comment] 2017-05-12 09:37
@asaunier As suggested, step 1 is implemented here https://github.com/c2corg/v6_ui/issues/1650

**Comment by asaunier** [comment] 2017-05-12 09:48
@olaurendeau That's soooooooo cool, thanks :) I'll have a look at your PR this WE I think.

**Comment by cbeauchesne** [comment] 2017-05-12 10:12
Hello guys,

Here is a set of unit tests, respecting the format I've committed yesterday : 
https://github.com/cbeauchesne/campui/blob/master/app/static/campui/js/tests/tests.json#L63-196

But as it includes 95% of L# specification, it may not a good idea to take it as is, you shall use only the part you support, otherwise your non-reg test will fail until you have coded everything.

And last but not least, they my be false because I've misunderstood specifications, feel free to challenge!

**Comment by olaurendeau** [comment] 2017-05-12 12:13
Thanks @cbeauchesne really useful :)

**Comment by cbeauchesne** [comment] 2017-05-12 14:18
It may be a better place to discuss this.

Regarding my comment on #1650 : 
> Although, I would recommend to not parse table if you are not sure that it respects the part of the spec you have implemented. Otherwise, you would introduce false interpretations that made most of topos false, and, worst, new topos will probably respects the newly interpretation, and it will be very difficult to correct everything later.

A good solution on unit test would be getting all my unit test, but for use case you still not support, commenting the good result and keeping the unmodifed code : 

```json
{
"id":"Not yet supported syntax",
"markdown":"L# strange feature",
"expected_but_later":"<strange result/>",
"expected":"L# strange feature"
}
```

Once you support this, you remove `expected`, and replace it by `expected_but_later`. With that, you ensure that you won't falsy interpret something.

**Comment by olaurendeau** [comment] 2017-05-13 19:27
Why not :)

**Comment by asaunier** [comment] 2017-06-02 12:42
The first version of the L# parser is now available in the demo.
Since there are still unsupported case, it is better to keep the issue open and remove the "ready for testing" label when tests are done.

**Comment by olaurendeau** [comment] 2017-06-02 13:43
How can we access the demo ? :)

**Comment by asaunier** [comment] 2017-06-02 13:45
@olaurendeau See http://www.demov6.camptocamp.org/ (c2corg/c2corg)

**Comment by olaurendeau** [comment] 2017-06-02 13:51
Great ;)
http://www.demov6.camptocamp.org/routes/794986/fr/vallee-d-ailefroide-eboulement-derborence I should have separated the L# and R# counters, this look a bit messy :)
I'll do a fix for that this weekend.

**Comment by desnoes** [comment] 2017-06-02 14:45
Nice job !

**Comment by cbeauchesne** [comment] 2017-06-03 15:38
hi @olaurendeau,

For this PR, do you parse all L# tags, included those with not suppported syntax, or do you kept them unchanged?

For instance, on this http://www.demov6.camptocamp.org/routes/57964/fr/aiguille-de-la-republique-republique-bananiere, numbering is wrong. 

An easy way to do this is testing the presence of unsupported syntax with this RE `L#[^:\| ]` ) would avoid false interpretations, and would avoid very big trouble imo.

**Comment by olaurendeau** [comment] 2017-06-04 08:24
Good point @cbeauchesne 
See https://github.com/c2corg/v6_ui/pull/1670 Fixing L/R separate counters + Ignoring pages with unsupported notation

**Comment by asaunier** [comment] 2017-06-08 07:44
@olaurendeau I have noticed a (not critical) issue with the translating of the generated "L" tags.
The generated HTML does contain the ``translate`` directive:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/ltag.py#L71
but the strings to translate are not extractable (because the i18n translator does not take markdown parsers into account and anyway the i18n strings are not explicitely shown in the code).

I think you have to add the L and R keyword to our i18n "fake" template (used to add by hand strings that must be extracted when they are not explicitely available in the real templates and JS files):
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/i18n.html
```
<span translate>L</span>
<span translate>R</span>
```

**Comment by asaunier** [comment] 2017-06-16 14:40
@olaurendeau Isn't the L# parser a bit too strict?
Sometimes when an unsupported tag is detected the whole L# parsing is skipped (crashed?). For instance http://www.demov6.camptocamp.org/routes/202439/fr/cogne-valeille-tuborg whose L# are all ignored because of the ``L#5`` (if I remove the 5, the whole parsing works).

**Comment by olaurendeau** [comment] 2017-06-16 14:57
I assume we can easily support the forced numbering :) let's say I'll
implement it next week
Point was raised by cbeauchesne that parsing unsupported tags would lead to
incoherences in routes description.
Le ven. 16 juin 2017 à 16:40, Alex Saunier <notifications@github.com> a
écrit :

**Comment by asaunier** [comment] 2017-06-16 14:59
> Point was raised by cbeauchesne that parsing unsupported tags would lead to
incoherences in routes description.

Isn't it better to have a minimal rendering (even if the numbering might be a bit wrong) rather than no rendering at all?

**Comment by olaurendeau** [comment] 2017-06-16 15:03
Point was that people may be tempted to fix the "bit wrong" numbering.
I don't have a strong position on this. Up to you :)
Le ven. 16 juin 2017 à 16:59, Alex Saunier <notifications@github.com> a
écrit :

**Comment by brunobesson** [comment] 2017-06-16 15:10
I would agree with @cbeauchesne and keep a protective approach. If there are special tags, the "default" rendering will introduce errors in the rendering, which might be wrose. We don't know what to correct then!

**Comment by olaurendeau** [comment] 2017-06-16 16:01
When a parsing is skipped, may could we add an information message explaining the user that "this document contain a yet unsupported Ltag that will soon be implemented" ?

**Comment by cbeauchesne** [comment] 2018-05-03 12:00
I close this issue, as it's now solved.

**Comment by brunobesson** [comment] 2018-05-03 12:02
Until now, we do not close an issue unless it arrived in production. Instead, we use the `ready for demo` and `ready for testing` labels.
In addition to this, I associated the milestone of the next release.

**Comment by brunobesson** [comment] 2018-05-03 12:27
My Bad, sorry. Can you make the appropriate corrections? I can't right
now...

**Comment by cbeauchesne** [comment] 2018-05-03 12:59
sure!

**Closed by cbeauchesne** 2018-05-03 12:59 UTC
Labels: Association, bug, parser, ready for demo
