### ISSUE TITLE
Filter organisation

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#858] opened 2016-11-05 18:40 UTC
The advanced filter list are not so logical some important criteria are at the end et some minor criteria at the beginning.
They are too many criteria, so lisibilité are not very good.

No discussion about relevant criteria but only optimize the order and grouping of criteria

- [ ] Grouping criteria by "logic" type ( rating, atltitude etc ...) and separate by line each group of criteria (as in v5 and airbnb)

Probably some needed discussion before starting anything ;-)

**Comment by desnoes** [comment] 2017-01-14 08:09
@stef74: to be done by the association ?

**Comment by stef74** [comment] 2017-01-14 09:00
Yes

**Comment by desnoes** [comment] 2017-02-04 09:21
Reorganozation is fine on desktop (could not test on mobile). There is however a problem with the display of fields at the bottom of the search window (cf #655).
![bug affichage filtres](https://cloud.githubusercontent.com/assets/19892089/22617373/ad73cbae-eac3-11e6-88ce-9f816d892e1e.jpg)

**Comment by stef74** [comment] 2017-02-04 19:48
ok

**Comment by desnoes** [comment] 2017-02-05 14:13
@stef74 : i think we can close this issue since the problem is already reported in #655

**Closed** 2017-02-06 13:13 UTC
Labels: advanced Search, Association, Ergo / Design, fixed and ready for testing
